- cea/properties.py
Fixed paths to new reference case location
> Fixed paths to new reference case location

- cea/emissions.py
- cea/functions.py
- cea/heatmaps.py
forgot to add the changes to functions.py (sync, then merge in future!)
> I114 update scripts

- cea/functions.py
@JIMENOFONSECA, @shanshanhsieh: I believe this change could fix shanshan's `MemoryError` problem. My strategy: Instead of summing all 8760 columns at once, group/sum them separately and then create the (much smaller) `DataFrame`.
Initial tests on @shanshanhsieh's computer show that they work, but TeamViewer decided to hang up on me so I finished the work on my computer.
I have run both versions and the results seem identical. @JIMENOFONSECA, you might want to check yourself?
I propose the OBM (Other Board Member) merges this pull request.
> this should solve the MemoryError shanshan is having

- cea/graphs.py
- cea/toolbox.py
check out this version of the demand graphs user interface.
I'm having a hard time to restrict selection of fields to 4 (arcpy is not calling updateParameters even though I think it should!)
but the tool only uses the first four selected.
BTW: @JIMENOFONSECA, what happens if only 3 are selected?
> I157 update toolbox for graphs

- cea/heatmaps.py
- cea/inputlocator.py
- cea/toolbox.py
and some fixes in the heatmaps script
> implemented toolbox for heatmaps

- cea/functions.py
It is renamed but not included in archetypes
> i49-Y-renaming

- cea/radiation.py
- sandbox/dthomas/functionlogger.py
- sandbox/dthomas/log_radiation.py
> I137 radiation script

- cea/functions.py
Bugs fixed in ventilation schedule and occupancy calculation
> I215 buxfix ve schedule

- cea/embodied.py
- cea/graphs.py
> Igraphs totals

- cea/thermal_loads.py
> bug fix required ventilation calculation

- cea/demand/thermal_loads.py
- tests/test_calc_thermal_loads_new_ventilation.py
Changed type of `tds`  to `dict` (was `Dataframe`)
> I 262 tds creating high overhead

- cea/demand/sensible_loads.py
- tests/test_calc_thermal_loads_new_ventilation.py
bug fixed.
script works.
but very different results!
> I277 bugfix thermal load

- cea/demand/thermal_loads.py
- cea/technologies/controllers.py
- cea/utilities/helpers.py
- starts demand calculation at the begin of the heating season
- allows to specifiy a dynamic warm up period
- overwrites warm up with results at the end of the cooling season
- uses current outdoor air temperature as initial guess of building
thermal mass and indoor air temperature
- also changes in ventilation calculation together with @JIMENOFONSECA
--> branch works, results look OK at first glance
--> but full testing can not be done until #293 is solved
> start with demand calculation before the beginning of the heating season (dynamic warm up phase)

- cea/plots/graphs.py
@daren-thomas i blelieve it should be working now, would you mind checking for me? merci
>  i287-problem-demand-graphs

- cea/GUI/toolbox.py
- cea/analysis/mobility.py
- cea/inputlocator.py
Added necessary getter functions to inputlocator and removed ExtendInputLocator class from mobility calculation.
> Removed ExtendInputLocator

- cea/GUI/toolbox.py
- cea/demand/thermal_loads.py
- cea/globalvar.py
- cea/plots/graphs.py
- tests/integration_test.py
implements #286 (multiprocessing for demand graphs) and fixes #309 (Key Error when running demand graphs from toolbox with certain analysis fields)
> I286 reduce calculation time for demand graphs

- cea/analysis/emissions.py
Fixes #305 (Running Emissions operation error)
> I305 running emissions operation error

- cea/GUI/toolbox.py
- cea/analysis/embodied.py
fixes #282 (SettingWithCopyWarning in `cea.analysis.embodied)
> I282 settingwithcopywarning in cea analysis embodied

- cea/demand/demand_main.py
- cea/globalvar.py
checked output with master - no discrepancies as far as I can tell...
> fixes #250

- cea/demand/demand_main.py
- cea/demand/thermal_loads.py
- cea/globalvar.py
- cea/inputlocator.py
- cea/plots/scenario_plots.py
- cea/utilities/solar_equations.py
- contributions/PV_generation_from_new_radiation_script/photovoltaic.py
- tests/create_unittest_data.py
- tests/test_calc_thermal_loads_new_ventilation.py
A photovoltaic.py script connecting to new radiation calculation results (from Paul) is added to the contribution.
To run the script, please add the example radiation result files to this path: C:\reference-case-zug\baseline\outputs\data\solar-radiation
Link to the example radiation result files: 
https://drive.google.com/folderview?id=0B0xYHrBRUcQoc1ByOHkzQnBXdEk&usp=sharing
> I290 pv generation from new radiation script

- cea/inputlocator.py
fixes the issue mentioned in #346 about the radiation script not running for the zug case study.
> create the solar radiation folder if it does not yet exist

- cea/demand/sensible_loads.py
- cea/demand/thermal_loads.py
I'm pulling these changes as they conflict with martins latest changes and I want to do the merge before everything get's really complicated.
> Documentation and refactoring

- cea/demand/demand_main.py
- cea/plots/graphs.py
- cea/plots/timeseries_interactive_graph.py
- tests/create_unittest_data.py
- tests/test_calc_thermal_loads_new_ventilation.py
This PR fixes the issue of pool.close() needing to be called in certain cases, especially if the code is being run from another process...
> fixes #350

- cea/demand/electrical_loads.py
> I360 calc eaf should be calculated based on aef

- .gitignore
- setup/Setup_CEAforArcGIS.iss
- setup/cealib.pth
- setup/copy_library.bat
- setup/copy_library.py
- setup/esri104.yml
add inno setup installer code for arcgis version of cea
> I355 create installer for arcgis version

- City Energy Analyst.pyt
- cea/GUI/radiation_tool.py
- cea/GUI/toolbox.py
this is a small fix for the gui of the radiation tool to allow overriding the latitude and longitude read from the shape files.
> Radiation script GUI with longitude and latitude fields

- cea/analysis/embodied.py
- cea/globalvar.py
> 147 refactor embodied.py

- setup/README.md
- setup/Setup_CEAforArcGIS.iss
> Finished installer for ArcGIS integration

- cea/plots/scenario_plots.py
> fixed error handling. error still get's thrown, but the files do not stay open.

- euler/README.md
Adding some more information on running on Euler in order to avoid mistakes (and thus avoid wasting time) when setting up simulations.
> Adding more info on running on Euler

- cea/interfaces/arcgis/CityEnergyAnalyst.py
- docs/environment.yml
- docs/getting-started.rst
@JIMENOFONSECA this should fix #571, a bug from one of our external users, as well as @amraladdin who has the same problem. Thing is, I broke the ArcGIS interface by accident.
> fixing the arcgis toolbox (import arcpy)

- cea/technologies/heating_coils.py
The previous pull request was a mess. This one is clean and simple.
> Replacing #576 

- cea/demand/airconditioning_model.py
Fixes #558 and replaces PR #559. The old pull request was a mess. This one is nice and clean.
> i558 Recirculation error fix - replaces PR #559 

- docs/installation-guide.rst
the installation still needs to be debugged by @daren-thomas
> I601 installation guide doc

- docs/documentation-guide.rst
- docs/index.rst
> minimalistic first stab at a documentation guide

- .gitignore
- MANIFEST.in
- cea/config.py
- cea/default.config
- cea/tests/test_is_heating_season.py
- docs/cascading-configuration-files.rst
cascading config files and a new way to specify heating seasons (and cooling seasons)
> Cascading config files

- cea/cli.py
- cea/demand/demand_main.py
- cea/demand/thermal_loads.py
- cea/interfaces/arcgis/CityEnergyAnalyst.py
implements #645 (switch between infiltration models) both for ArcGIS and for CLI.
> 645 switch between infiltration models

- cea/default.config
- cea/demand/occupancy_model.py
- cea/tests/create_unittest_data.py
- cea/tests/test_calc_thermal_loads.py
- cea/tests/test_schedules.py
This PR fixes the errors in the unit tests in PR #675, which broke the build.
> I688 fix broken build

- cea/demand/preprocessing/properties.py
- cea/demand/thermal_loads.py
This pull request solves any discrepancies created by an incorrect renovation year being specified. If renovation year =< construction year, an appropriate warning appears and the construction year is used in place of the renovation year.
> I372 data helper discrepancy

- cea/resources/radiation_arcgis/radiation.py
> fixing special case radiation

- cea/interfaces/arcgis/CityEnergyAnalyst.py
- cea/utilities/dbfreader.py
> xls2dbf_new_branch

- cea/interfaces/arcgis/CityEnergyAnalyst.py
- cea/utilities/dbfreader.py
Reverts architecture-building-systems/CEAforArcGIS#714
(not quite ready for production yet)
> Revert "xls2dbf_new_branch"

- cea/demand/sensible_loads.py
- cea/demand/thermal_loads.py
fix conditioned area correction for buildings with only cooling systems
> I733 cooling conditioned buildings

- cea/demand/thermal_loads.py
A warning appears for any building that has no heating or cooling systems. This warning was meant to appear only in the case where a building has no heating or cooling systems **and** has a conditioned floor area greater than 0.
> I766 Remove unnecessary error message

- cea/interfaces/arcgis/CityEnergyAnalyst.py
- cea/tests/dodo.py
> 768 add an interface to extract reference case to the arcgis toolbox

- docs/installation-guide.rst
- environment.yml
@JIMENOFONSECA this is a simplified way to install the CEA based on git and environment.yml.
> 2017 08 09 easier installation guide

- cea/analysis/lca/mobility.py
- cea/resources/radiation_daysim/create_gml.py
- cea/resources/radiation_daysim/geometry_generator.py
- cea/resources/radiation_daysim/radiation_main.py
- cea/utilities/solar_equations.py
- docs/cascading-configuration-files.rst
- docs/index.rst
- docs/modules/cea.analysis.lca.rst
- docs/modules/cea.analysis.retrofit.rst
- docs/modules/cea.analysis.rst
- docs/modules/cea.analysis.sensitivity.rst
- docs/modules/cea.analysis.uncertainty.rst
- docs/modules/cea.databases.rst
- docs/modules/cea.interfaces.arcgis.rst
- docs/modules/cea.interfaces.rst
- docs/modules/cea.plots.rst
- docs/modules/cea.resources.radiation_arcgis.rst
- docs/modules/cea.resources.radiation_daysim.rst
- docs/modules/cea.resources.rst
- docs/modules/cea.rst
- docs/modules/cea.technologies.heating-network.rst
- docs/modules/cea.technologies.rst
- docs/modules/cea.tests.rst
- docs/modules/cea.utilities.rst
- docs/modules/modules.rst
this fixes failing sphinx builds... temporarily: i'll have to do something similar every now and then just to make sure everything is a-ok.
> updates to the documentation - sphinx now builds without warnings

- docs/conf.py
- docs/environment.yml
- environment.yml
- readthedocs.yml
- setup.py
This PR fixes failing builds on the http://city-energy-analyst.readthedocs.io site.
@JIMENOFONSECA please merge this.
> Readthedocs - fix build errors in rtd

- docs/installing-the-jenkins.rst
still working on configuring the jenkins...
> 695 document the jenkins setup

- cea/demand/electrical_loads.py
- cea/demand/thermal_loads.py
- including additional types (T0, T1, T4, T5) with zero electricity in
calculation
- refactoring
- moving function to electrical loads script
- documentation
> including centralized supply systems in building HP electricity calculation

- cea/optimization/master/check.py
- cea/optimization/master/master_main.py
changing the mutation strategy to an effective strategy based on the preliminary study. The research on this will still be continued to better the mutation strategy, but for now this decreases the number of function evaluations yet keeping the accuracy
> changing the mutation strategy

- cea/optimization/master/evaluation.py
a minor change to avoid long file names. Using this, the saved files will still have the supply system, followed by building network (in the form of hexadecimal string)
> conversion into hexadecimal notation

- docs/installation-guide.rst
@JIMENOFONSECA here is an update to a commit you made for the installation guide. Part of your commit could be read in a sense that was technically incorrect and while trying to fix that sentence I decided to just reformulate the whole thing. Does this get the same message across, what do you think?
> 2017 11 20 small fix to installation guide

- cea/__init__.py
- environment.yml
> relaxing restrictions on some packages

- cea/analysis/sensitivity/sensitivity_demand_simulate.py
- cea/demand/demand_main.py
- cea/demand/metamodel/nn_generator/install tensorflow.md
- cea/tests/create_unittest_data.py
- cea/tests/test_check_for_radiation_input_in_demand_script.py
@daren-thomas so this should solve the problems with the sensitivity analysis. The unitests were updated to use also daysim radiation (which takes less than a minute to complete for the open case), so, to run the tests, it needs to run radiation daysim first.
> 930 sensitivity broken

- cea/config.py
- cea/default.config
- cea/interfaces/arcgis/install_toolbox.py
- cea/interfaces/arcgis/test.pyt
- cea/interfaces/cli/cli.config
- cea/technologies/solar/photovoltaic.py
- cea/technologies/solar/photovoltaic_thermal.py
- cea/technologies/solar/solar_collector.py
> 945 modify dynamic supply systems interface

- cea/interfaces/arcgis/install_toolbox.py
I forgot to comment out a line. My bad.
> i forgot to comment out the creation of test.pyt on `cea install-toolbox`

- cea/demand/rc_model_crank_nicholson_procedure.py
- cea/plots/color_code.py
- cea/plots/demand/dashboard_building.py
- cea/plots/demand/dashboard_district.py
- cea/plots/demand/energy_balance.py
- cea/plots/demand/energy_demand.py
- cea/plots/demand/energy_use_intensity.py
- cea/plots/demand/heating_reset_schedule.py
- cea/plots/demand/load_curve.py
- cea/plots/demand/load_duration_curve.py
- cea/plots/demand/peak_load.py
- cea/plots/optimization/pareto_capacity_installed.py
- cea/plots/solar_potential/solar_radiation.py
- cea/plots/solar_potential/solar_radiation_curve.py
- cea/plots/solar_potential/solar_radiation_monthly.py
- cea/plots/variable_naming.py
@shanshanhsieh this adds the colors to new variables, would you mind adding a review?
> colors added as a class

- docs/environment.yml
See this link to view a build in the `readthedocs` branch that was updated to match master, then 999-read-the-docs-broken. Check this link to view it in action: http://city-energy-analyst.readthedocs.io/en/readthedocs/
> this should fix #999

- cea/technologies/substation_matrix.py
- cea/technologies/thermal_network/thermal_network_matrix.py
switched keyword from "is" to "=="
> i997_thermal_network_matrix_does_not_run_for_DH

- cea/optimization/master/master_main.py
This PR fixes the issue faced while saving the files in the checkpoints
> I1012 inconsistent saving of files opt

- cea/default.config
- cea/plots/color_code.py
- cea/plots/demand/dashboard_building.py
- cea/plots/demand/dashboard_district.py
- cea/plots/life_cycle/dashboard_district.py
- cea/plots/life_cycle/emissions.py
- cea/plots/life_cycle/emissions_intensity.py
- cea/plots/life_cycle/primary_energy.py
- cea/plots/life_cycle/primary_energy_intensity.py
- cea/plots/optimization/dashboard_district.py
- cea/plots/optimization/dashboard_individual.py
- cea/plots/optimization/load_profile_plot.py
- cea/plots/optimization/pareto_activation_curve.py
- cea/plots/solar_potential/dashboard_building.py
- cea/plots/solar_potential/dashboard_district.py
- cea/plots/solar_technology_potentials/dashboard_district.py
@martin-mosteiro would you mind checking this PR for me?
How to run?
1. erase config file in userprofile.
2. run Dashboard_district.py located in cea/plots/lca/...
Expected results:
5 graphs should be saved in  outputs/plots
> I1049 life cycle

- cea/inputlocator.py
@daren-thomas this is a small fix to ensure a folder in the input locator. would you mind taking a look? thanks!
> fixing path so Singapore case study works

- cea/demand/sensible_loads.py
- cea/demand/thermal_loads.py
a small addition and refactoring in the demand calculation that unfortunately somehow got lost in the reverted PR of issue #1132
> refactoring and re-adding final heating and cooling demand calc

- cea/technologies/thermal_network/thermal_network_matrix.py
Found ad fixed the unit error in the thermal network matrix script.
@JIMENOFONSECA can you check if this solves the issue you found?
> Fix to unit problem in thermal network matrix

- cea/plots/demand/comfort_chart.py
- cea/plots/demand/dashboard_district.py
minor improvements plus major documentation for comfort plot
> I 209 clean and documented comfort plot

- cea/technologies/solar/photovoltaic_thermal.py
this PR resolves #1217 
to test: run `photovoltaic_thermal.py`
> fix mcp_kWperK list type

- docs/installation-guide-ubuntu.rst
- docs/installation-on-windows.rst
i have included dl and install of git for both ubuntu and windows install documentation.
> Updated installation doc

- docs/installation-on-windows.rst
removed adding cea env to path
> 1252-cea-installation

- cea/config.py
- cea/default.config
- cea/inputlocator.py
- cea/interfaces/arcgis/CityEnergyAnalyst.py
- cea/interfaces/arcgis/arcgishelper.py
- cea/interfaces/arcgis/install_toolbox.py
- cea/interfaces/arcgis/list_buildings.py
- cea/interfaces/arcgis/test.pyt
The plotting interface for ArcGIS has been upgraded to show a list of buildings and also update that list when a new scenario is chosen. This fixes #1222
> 1222 ploting interface for arcgis should show list of buildings

- cea/optimization/preprocessing/disconnected_buildings_heating.py
- cea/optimization/slave/seasonal_storage/SolarPowerHandler_incl_Losses.py
- cea/optimization/slave/seasonal_storage/design_operation.py
- cea/plots/optimization/main.py
- cea/technologies/solar/photovoltaic.py
- cea/technologies/substation.py
This PR should fix the bug in the master. The bug arised because the substation file is not being run in the dencentralized_buildings_heating scenario. This PR fixes it. Also when I am at it did some minor refactoring in storage files. 
To test it, run the decentralized_main, followed by optimization. Follow this with running the plots
> I1305 bug in master

- cea/default.config
- cea/interfaces/cli/cli.config
- cea/technologies/solar/photovoltaic.py
- cea/technologies/solar/photovoltaic_thermal.py
- cea/technologies/solar/solar_collector.py
- cea/utilities/solar_equations.py
This PR resolves issue #1329, #1331, #1332 
Changes include: 
1. maximum radiation received on surface setting
2. radiation on surface threshold (from percentage to a fixed number, it was suggested during the test run, part of #1245)
To test:
1. delete `cea.config`
2. change region/weather to SIN/Singapore-2016
3. `install_toolbox`
4. run `photovoltaic.py`, `solar_collectors.py`, `PVT` tools from ArcGIS
> I1331 pv panels fail to run

- cea/demand/demand_writers.py
This PR replaces a line that caused output csv files to have duplicate columns. Solves issue #1344.
> Demand script output csv columns

- cea/plots/solar_technology_potentials/all_tech_yearly.py
- cea/plots/solar_technology_potentials/pv_monthly.py
- cea/plots/solar_technology_potentials/pvt_monthly.py
- cea/plots/solar_technology_potentials/sc_monthly.py
to test: 
- produce solar technology potential outputs with zeros, it can be done by setting the annual-radiation-threshold to a very high value (=3000000) 
- run the plots under `plots/solar_technologies_potentials/main.py`
you should see this: 
- nothing in the graph
- 0 (0%) in the table
> i1369 fix solar technology potential plot when there the total potential is zero

- cea/analysis/lca/operation.py
@BhargavaKrishnaSreepathi would you mind checking if this works?
you need to run emissions_operation form the lca assessment
> fix so we do not double account emissions

- cea/interfaces/arcgis/CityEnergyAnalyst.py
- cea/interfaces/arcgis/arcgishelper.py
- cea/interfaces/arcgis/test.pyt
This fixes #1389 - it seems there was a race condition in the handling of the weather_name/weather_path parameters: it worked on my computer, but didn't work on those in the lab.
> 1389 weather file cannot be changed from arcgis interface

- cea/interfaces/arcgis/CityEnergyAnalyst.py
just a simple change to CityEnergyAnalyst.pyt. to test, run `cea install-toolbox` and restart ArcGIS.
> fixes #1323

- docs/main-developer-workflow.rst
changes to formatting and addition of detailed information
> 907-minor additions

- cea/demand/occupancy_model.py
- docs/cea-workflow-guide.rst
minor documentation build errors addressed
> 1404 api demand occupancy model

- bin/ceatest.bat
- bin/ceatestall.bat
let's see if this runs through
> this should fix the failing jenkins tests

- cea/demand/building_properties.py
i've addressed the sphinx build errors and tried to add some documentation however this should be reviewed
> 1298 api demand building properties

- cea/plots/optimization/cost_analysis.py
- cea/plots/optimization/cost_analysis_curve_centralized.py
- cea/plots/optimization/cost_analysis_curve_decentralized.py
- cea/plots/optimization/individual_activation_curve.py
This PR changes the plot from a `stack` to `relative`. So the negative values dont mess up the way the plots look. This directly solves the issue #1423
> Fixes to stack plots

- docs/cea-workflow-guide.rst
> update documentation with new names for solar collectors

- cea/interfaces/arcgis/modules.py
Fixes the error on martin's computer
> 1335 import arcgisscripting ImportError: DLL load failed: %1 is not a valid Win32 application.

- cea/analysis/retrofit/retrofit_potential.py
This PR solves a KeyError issue in the retrofit potential script as well as updating the cost threshold calculations to account for the keys in the new outputs from `operation_costs.py`
> I1476 retrofit potential tool keyerror qhsf mwhyr

- bin/cea-workflow.bat
this makes the cea-workflow.bat easier to use (just one variable, the scenario is used. that is necessary for the logging of the progress... all other data is taken from the config file)
> update to cea-workflow.bat

- cea/config.py
- cea/default.config
- cea/technologies/solar/photovoltaic.py
- cea/technologies/solar/photovoltaic_thermal.py
- cea/technologies/solar/solar_collector.py
- cea/utilities/solar_equations.py
This pull request fixes a small bug in the configuration file with a hasty renaming of a configuration variable (`{solar:annual-radiation-threshold}`)
> BUGFIX for solar:annual-radiation-threshold

- bin/cea-workflow.bat
- cea/plots/heatmaps.py
there was a bug in the heatmaps that got triggered by the new field names (longer than 10 characters).
this is an attempt to fix it.
> fixing heatmaps

- cea/plots/demand/energy_balance.py
- cea/plots/demand/energy_use_intensity.py
- cea/plots/demand/main.py
- cea/plots/demand/peak_load.py
additionally normalizes individual building monthly energy balance by GFA as well.
> fixes i1527

- cea/plots/naming.csv
- cea/plots/thermal_networks/annual_energy_consumption.py
- cea/plots/thermal_networks/main.py
This PR resolves #1494
One plot, `annual_energy_consumption.py`, is added to the network plots
> I1494 update network plots

- cea/optimization/lca_calculations.py
- cea/plots/comparisons/operation_costs.py
- cea/plots/supply_system/main.py
@daren-thomas this fixes an issue we found during testing today evening. It is the issue that arcgis blocks scripts trying to use the backdoor of the config file. Things work now.
> Fixes for 4day

- cea/plots/comparisons/main.py
- cea/plots/naming.csv
This PR solves an issue with the comparison plots, where the primary energy and emission intensity (i.e., per square meter) were calculated incorrectly.
> I1569 lca comparison plots

- cea/resources/radiation_daysim/daysim_main.py
this solves #1635 
@daren-thomas could you check this PR please? thanks!
> fix error message radiation daysim

- cea/datamanagement/create_new_project.py
- cea/datamanagement/databases_verification.py
- cea/resources/radiation_daysim/geometry_generator.py
- cea/resources/radiation_daysim/radiation_main.py
> I1557 none error

- cea/demand/building_properties.py
- cea/demand/space_emission_systems.py
this solves issue #1511 
@gabriel-happle would you like to verify if this patch solves the problem?
> adding flag to solve issue

- CREDITS.md
- cea/__init__.py
- cea/optimization/slave/electricity_main.py
- cea/scripts.yml
- cea/supply/supply_system_simulation.py
This is it: The final version we will release as 2.9.0 - currently, it is set to 2.9.0a0 while I test the installer. Once that works, we can change the version number and merge, create branch, upload to PyPI.
> Release 2.9.0

- docs/how-to-contribute.rst
- docs/how-to-document-cea.rst
Updated the how to document cea rst file.
Open for feedback
> 1666 how to document cea update

- docs/glossary.rst
- docs/how-to-contribute.rst
- docs/known-issues.rst
Hallo Jimeno,
is this something along the lines of what you were thinking?
My programming skills are not strong enough to interface with Github and pull the information from the open issues into an rst table.
I'm only really using the table for the existing issues for which I could only find one link. 
Welcome to feedback as always
> 1239 known issues table ref

- cea/analysis/sensitivity/sensitivity_demand_simulate.py
- cea/analysis/uncertainty/Individual_Evaluation.py
- cea/demand/metamodel/nn_generator/input_matrix.py
- cea/demand/metamodel/nn_generator/input_prepare.py
- cea/demand/metamodel/nn_generator/nn_random_sampler.py
- cea/demand/metamodel/nn_generator/nn_test_sampler.py
- cea/demand/metamodel/nn_generator/nn_trainer_estimate.py
- cea/demand/metamodel/nn_generator/scaler_sampler.py
- cea/globalvar.py
- cea/optimization/individual_evaluation/individual_cooling_main.py
- cea/optimization/master/check.py
- cea/optimization/preprocessing/decentralized_buildings_heating.py
- cea/optimization/slave/cooling_main.py
- cea/optimization/slave/heating_main.py
- cea/resources/geothermal.py
- cea/resources/sewage_heat_exchanger.py
- cea/technologies/pumps.py
- cea/technologies/substation.py
- cea/utilities/solar_equations.py
One more step to get rid of GV
> taking gv out of neural network

- cea/analysis/sensitivity/sensitivity_demand_simulate.py
- cea/default.config
- cea/demand/calibration/subset_calibrator/surrogate_4_calibration.py
- cea/demand/metamodel/nn_generator/nn_random_pipeline.py
- cea/demand/metamodel/nn_generator/nn_random_sampler.py
- cea/demand/metamodel/nn_generator/nn_test_sampler.py
- cea/demand/metamodel/nn_generator/nn_trainer_evaluate.py
- cea/optimization/master/evaluation.py
- cea/optimization/slave/cooling_main.py
- cea/supply/supply_system_simulation.py
> #753 get rid of gv

- cea/analysis/clustering/sax/sax_optimization.py
- docs/make-api-doc.bat
There was a minor error in the sax_optimisation.py imports
> Autodoc import error fixed for analysis/clustering

- docs/installation-on-windows.rst
Updated ArcGIS installation to include Background Geoprocessing and disclaimer regarding visualisation. 
Open for additions.
> updated ArcGIS install instructions

- cea/inputlocator.py
- cea/technologies/solar/photovoltaic.py
- cea/technologies/solar/photovoltaic_thermal.py
- cea/technologies/solar/solar_collector.py
this PR creates an additional output file for each solar technology with aggregated annual results of all buildings in a district
to test:
1. run `photovoltaic.py`, check the file `PV_total_buildings.csv'
2. run `solar_collector.py`, check the file `SC_tech_total_buildings.csv`
3. run `photovoltaic_thermal.py`, check the file `PVT_total_building.csv`
> add new files to output annual aggregation per building

- bin/ceatest.bat
- cea/demand/calibration/bayesian_calibrator/calibration_main.py
- cea/demand/thermal_loads.py
- cea/inputlocator.py
- cea/tests/dodo.py
- environment.yml
more fixes to the environment.yml file. also, some small fixes to reduce the time for the jenkins test.
to test, delete the environment and recreate:
- `conda env remove -n cea`
- `conda env create`
- `pip install -e .`
- `cea test`
> 1734 importerror dll load failed fiona ogrext

- cea/inputlocator.py
- cea/technologies/thermal_network/network_layout/connectivity_potential.py
- cea/technologies/thermal_network/network_layout/main.py
- environment.yml
- legacy/radiation_arcgis/radiation.py
this might solve #1764. i need to merge to find out...
> a more robust way of getting a Default.gdb workspace for arcgis

- cea/technologies/thermal_network/thermal_network_matrix.py
Some files were not created during representative week thermal network simulations - thus, the plots could not be created for these cases. This PR fixes that issue.
> Add missing file outputs from representative week method

- cea/optimization/constants.py
- cea/optimization/individual_evaluation/individual_cooling_main.py
- cea/optimization/master/cost_model.py
- cea/optimization/slave/cooling_main.py
- cea/optimization/slave/heating_resource_activation.py
Fixing a refactoring bug present in Master. This was affecting optimization script.
The way to test the script is to start a fresh test case and test optimization. More details can be found here 
https://city-energy-analyst.readthedocs.io/en/latest/cea-workflow-guide.html 
Look at step 9
Martin, I am assigning you such that you can test your bug in this branch and suggest if there needs to be any changes
> Fixing calc cop ccgt

- cea/analysis/multicriteria/main.py
- cea/analysis/multicriteria/optimization_post_processing/individual_configuration.py
- cea/analysis/multicriteria/optimization_post_processing/locating_individuals_in_generation_script.py
- cea/analysis/uncertainty/Individual_Evaluation.py
- cea/default.config
- cea/interfaces/dashboard/dashboard.py
- cea/interfaces/dashboard/plots/static/js/dashboard-plots.js
- cea/interfaces/dashboard/plots/templates/dashboard.html
- cea/optimization/individual_evaluation/individual_cooling_main.py
- cea/optimization/lca_calculations.py
- cea/optimization/master/cost_model.py
- cea/optimization/master/master_main.py
- cea/optimization/optimization_main.py
- cea/optimization/preprocessing/decentralized_building_main.py
- cea/optimization/preprocessing/decentralized_buildings_cooling.py
- cea/plots/__init__.py
- cea/plots/base.py
- cea/plots/categories.py
- cea/plots/demand/comfort_chart.py
- cea/plots/optimization/__init__.py
- cea/plots/optimization/centralized_costs_per_generation_unit.py
- cea/plots/optimization/cost_analysis_centralized_system.py
- cea/plots/optimization/main.py
- cea/plots/optimization/pareto_capacity_installed.py
- cea/plots/optimization/pareto_curve.py
- cea/plots/supply_system/main.py
- cea/scripts.yml
- cea/supply/supply_system_simulation.py
- cea/technologies/solar/photovoltaic.py
- cea/technologies/thermal_network/thermal_network_costs.py
Steps to test:
- scenario must be able to run `cea plots-optimization`
- run `cea dashboard`
- add plots to the dashboard 
- use category "Optimization overview"
- try all four plots
NOTE: I have not tested this with `network-type == 'DH'`
> 1762 add optimization plots to the dashboard

- cea/optimization/individual_evaluation/individual_cooling_main.py
- cea/optimization/lca_calculations.py
- cea/optimization/preprocessing/decentralized_building_main.py
- cea/optimization/preprocessing/decentralized_buildings_cooling.py
- cea/scripts.yml
This is a fix for the [issue raised in #1825 by Jack](https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1825#issuecomment-476747804).
I pushed an incomplete refactoring.
> 1825 lca calculations fix

- cea/technologies/thermal_network/network_layout/connectivity_potential.py
- cea/technologies/thermal_network/network_layout/steiner_spanning_tree.py
@martin-mosteiro kindly, cross-check this. The PR is ready to merge though
> I1836 network layout

- cea/datamanagement/create_new_project.py
- cea/datamanagement/databases_verification.py
- cea/datamanagement/district_geometry_helper.py
- cea/datamanagement/streets_helper.py
- cea/datamanagement/terrain_helper.py
- cea/default.config
- cea/demand/constants.py
- cea/resources/radiation_daysim/geometry_generator.py
- cea/scripts.yml
- environment.yml
This solves issue #1849 and #1851  which introduces three new tools for CEA
To test:
Run 
datamanagement/district-helper.py
datamanagemnet/streets-helper.py
datamanagemnet/terrain-helper.py
It should create respectively the district.shp, the streets.shp and the terrain.tiff for your scenario>
Then run radiation, so to check that the geometry works.
> Automated generation of streets and district file from Open Street Maps for CEA

- docs/config-file-guide.rst
- docs/how-to-add-a-new-script-to-the-cea.rst
- docs/how-to-create-a-new-release.rst
- docs/how-to-document-cea.rst
- docs/how-to-prepare-inputs-for-network-simulation.rst
- docs/how-to-publish-cea.rst
- docs/how-to-report-bugs.rst
- docs/how-to-run-thermal-network-optimization.rst
- docs/how-to-test-the-cea.rst
- docs/how-to-use-github.rst
- docs/known-issues.rst
- docs/new-project-guide.rst
- docs/tutorials.rst
fixed the broken link for ``how to document cea``
improved the consistency of titles
> 1875 fix broken link on dev tutorials

- cea/analysis/multicriteria/optimization_post_processing/energy_mix_based_on_technologies_script.py
This PR fixes the function call in the issue #1841. @JIMENOFONSECA: the function call is now updated
> i1841 Incomplete function call in energy_mix_based_on_technologies_script.py

- cea/optimization/optimization_main.py
While trying to reproduce #1827, I made some small changes to optimization_main.py - cleaning up. This is a really small PR, but I guess we could do a lot of these to tidy up optimization and get it ready for cloud.
BTW: I can't reproduce #1827. I do not see the config file being reset no matter how many times I run optimization or optimization plots.
> 1827 config file is getting reset to default values after running scripts

- docs/cea-workflow-guide.rst
@Jack-Hawthorne would you mind checking this PR for me? It just updates the workflow of CEA with the new dashboard and the new data helper, district helper, terrain helper and streets helper tools
> I1907 docu new project

- cea/datamanagement/district_geometry_helper.py
- cea/datamanagement/zone_helper.py
- cea/default.config
@reyery this solves issues #1924 and #1920, 
To test, just use the site shapefile and run the zone_helper. It should create the zone.shp, occupancy and age.dbf based on data in Open street maps
> adding automatic occupancy of site

- cea/datamanagement/district_geometry_helper.py
- cea/datamanagement/zone_helper.py
- cea/interfaces/dashboard/inputs/inputs.yml
- cea/interfaces/dashboard/inputs/routes.py
This PR resolves #1935. The 'data_source' column is now added to the inputs.yml for the four databases. It should also be noted that the columns in shape files are truncated to 10 characters due to specification of the format.
> Add data_source to input table in dashboard

- cea/analysis/uncertainty/Uncertainty_parameters.py
- cea/demand/occupancy_model.py
- cea/resources/radiation_daysim/visualization.py
Some more small fixes towards closing #753. There is still more work to be done. See the issue.
> 753 remove globalvars

- CREDITS.md
- bin/create-changelog.py
- cea/__init__.py
- docs/how-to-create-a-new-release.rst
- docs/how-to-run-CEA-optimization.rst
- docs/how-to-run-MPC-district.rst
- docs/how-to-run-thermal-electrical-grid-planning.rst
- docs/installation-on-windows.rst
This pull request contains the state of the code as pushed to PyPI as release 2.14
> Release 2.14

- cea/config.py
- cea/plots/__init__.py
- cea/plots/base.py
- cea/plots/categories.py
- cea/plots/demand/__init__.py
- cea/plots/demand/energy_demand.py
- cea/plots/solar_potential/__init__.py
- cea/plots/solar_potential/solar_radiation.py
- cea/plots/solar_potential/solar_radiation_curve.py
- cea/plots/solar_potential/solar_radiation_monthly.py
This PR adds the solar potential plots to the dashboard:
- solar-radiation-monthly
- solar-radiation-curve
- solar-radiation-per-building
To test, run the dashboard and add the three plots to the dashboard.
> 1982 add solar potential plots to the dashboard

- cea/interfaces/cli/cli.py
- cea/plots/base.py
- cea/plots/demand/__init__.py
- cea/plots/life_cycle/__init__.py
- cea/plots/life_cycle/emissions.py
- cea/plots/life_cycle/emissions_intensity.py
- cea/plots/life_cycle/operation_costs.py
- cea/plots/life_cycle/primary_energy.py
- cea/plots/life_cycle/primary_energy_intensity.py
- cea/plots/solar_potential/__init__.py
- cea/plots/solar_potential/solar_radiation_curve.py
This PR implements the life cycle plots for #1985.
To test, run dashboard and add all the life cycle plots. Test changing parameters.
@reyery please check this and merge so I can continue plotting
> 1985 add life cycle plots to the dashboard

- cea/datamanagement/district_geometry_helper.py
- cea/datamanagement/zone_helper.py
- cea/demand/building_properties.py
- cea/interfaces/dashboard/tools/routes.py
This PR resolves #2011 #2012 #2013. They help solve some of the bugs that exist in the `district` and `zone` tool.
> 2013 2012 2011 helper tool bugs

- docs/installation-on-windows.rst
This fixes the issue in #1988 
@gabriel-happle could you please review this for me? thank you!
> fixes #1988

- cea/plots/demand/energy_balance.py
- change sign of `I_rad` (line 170 and 171)
- plus some pep8 in the file
Testing by running the energy balance plot and checking if I_rad is < 0 
(previously it was >0)
> fixes building energy balance plots

- CHANGELOG.md
- CREDITS.md
- bin/create-changelog.py
- cea/__init__.py
- setup/cityenergyanalyst.nsi
Culmination of the M2.15 sprint. Changes:
2019-06-04 - 2.14 - #2035 fixes building energy balance plots
2019-06-04 - 2.14 - #2042 fixes #1988
2019-06-03 - 2.14 - #2029 1761 fix grasshopper installer script
2019-05-30 - 2.14 - #2028 Steiner tree and buildings with no demand
2019-05-30 - 2.14 - #2019 1983 add solar technologies plots to the dashboard
2019-05-30 - 2.14 - #1994 Missing cool room and server room loads
2019-05-27 - 2.14 - #1998 I1958 cooling case workflow not working
2019-05-27 - 2.14 - #2009 Closes #1985 add life cycle plots to the dashboard
2019-05-24 - 2.14 - #2003 Closes #1982
2019-05-23 - 2.14 - #2000 I1950 remove arcgis radiation
2019-05-23 - 2.14 - #1997 1987 fix qt conf for installer
2019-05-23 - 2.14 - #1903 Make each function that has occupants have a minimum of one …
> Release 2.15

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
- setup.py
- setup/cityenergyanalyst.nsi
This is the result of the M2.16 sprint which contained a lot of work on the Dashboard and bug fixes.
> Release 2.16

- docs/how-trace-inputlocator-works.rst
- docs/tutorials.rst
has some inclusions once the glossary PR is finished
> Updated documentation to include trace-inputlocator

- cea/plots/demand/energy_demand.py
- cea/plots/demand/energy_supply.py
- cea/plots/demand/energy_supply_intensity.py
- cea/plots/demand/energy_use_intensity.py
- cea/plots/demand/heating_reset_schedule.py
- cea/plots/demand/load_duration_curve.py
- cea/plots/demand/load_duration_curve_supply.py
- cea/plots/demand/peak_load.py
- cea/plots/demand/peak_load_supply.py
- cea/plots/naming.csv
@martin-mosteiro this should solve #1834. just go ahead and merge if the names make sense now
> I1834 description variables

- cea/interfaces/dashboard/base/static/build/css/custom.css
- cea/interfaces/dashboard/base/static/build/js/glossary_search.js
- cea/interfaces/dashboard/inputs/routes.py
This PR fixes minor bug described in #2125.
> Minor bugfix for glossary frontend

- cea/interfaces/dashboard/base/routes.py
- cea/interfaces/dashboard/base/static/build/css/custom.css
- cea/interfaces/dashboard/base/templates/errors/page_500.html
This PR resolves #2132.
Features
---
- New `500` status error page that shows the user the stack trace of the error to help with more informative error/issue reporting.
> FEATURE: New 500 status error page

- cea/interfaces/dashboard/base/templates/site_template/sidebar.html
- docs/known-issues.rst
@reyery this solves the link to known issues (it will show open and closed) in our docs and the CEA dashboard 'known issues'
> Fix to known issues

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
- setup/cityenergyanalyst.nsi
This PR closes M2.18 and provides the release v2.18
> Release 2.18

- docs/how-are-schedules-defined.rst
Fixed some issues with the schedules documentation, namely the error in formula for T01.
> edited schedules documentation

- cea/interfaces/dashboard/inputs/inputs.yml
- cea/interfaces/dashboard/inputs/routes.py
currently the indoor comfort data is missing in the dashboard input editor.
This PR fixes it.
> adding comfort to dashboard

- cea/demand/control_heating_cooling_systems.py
This fixes bug #2195 . 
How to test:
- run the demand of @JIMENOFONSECA's case study in master with region CH and weather Zug, it should fail with error: `ValueError: cannot convert float NaN to integer`
- run the demand of the same case study in this branch: it should pass
Let me know if you need the case study. I can send it to you.
> I2195 fix vectorized setpoint

- cea/interfaces/dashboard/plots/templates/layout/layout_container.html
- cea/interfaces/dashboard/plots/templates/layout/map_layout.html
- cea/interfaces/dashboard/plots/templates/layout/row_layout.html
This PR resolves #2190
This adds the "change plot" button to the plot title bar in row layout which already exist in the map layout of the dashboard.
> Add "change plot" button to row layout

- cea/interfaces/dashboard/base/static/vendors/jquery-ui/jquery-ui.css
- cea/interfaces/dashboard/base/static/vendors/jquery-ui/jquery-ui.js
- cea/interfaces/dashboard/base/templates/base_site.html
- cea/interfaces/dashboard/inputs/static/js/mapclass.js
- cea/interfaces/dashboard/plots/templates/layout/layout_container.html
- cea/interfaces/dashboard/plots/templates/layout/row_layout.html
- cea/interfaces/dashboard/plots/templates/plot_widget_macros.html
This PR resolves #2214.
Fixes
---
- Add tooltips to plot buttons to describe their function
- Moved `jquery-ui` library to local instead of using link
- Ensure that the buttons of the map in dashboard map layout have bootstrap tooltips.
> Minor Fix: Add tooltips to plot buttons

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
This is the result of the M2.19 sprint which contained a bunch of improvements to the CEA Dashboard interface as well as a lot of work on heating case optimization.
To install it on windows, download and run Setup_CityEnergyAnalyst_2.19.exe. See the guide for more options.
2019-07-29 - 2.18.1 - #2215 Minor Fix: Add tooltips to plot buttons
2019-07-25 - 2.18.1 - #2209 Add "change plot" button to row layout
2019-07-24 - 2.18.1 - #2191 I2182 read occupancy schedules
2019-07-24 - 2.18.1 - #2203 Closes #2202
2019-07-24 - 2.18.1 - #2199 Heating case workflow
2019-07-23 - 2.18.1 - #2193 2143 document and proof default config
2019-07-23 - 2.18.1 - #2196 I2195 fix vectorized setpoint
2019-07-23 - 2.18.1 - #2161 don't create the inputs folder when opening a project + scenario …
> Release 2.19

- cea/interfaces/dashboard/inputs/routes.py
Fixes
---
- Fixes a bug where the original projected coordinate system is not saved when saving changes in the input editor of the dashboard.
> Bugfix: Calculate and save projected coordinate system

- cea/demand/occupancy_model.py
- cea/inputlocator.py
> fix occupancy

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
- cea/tests/dodo.py
- cea/utilities/standardize_coordinates.py
This is the result of the M2.20 sprint which contained a lot of work on heating and cooling case optimization.
To install it on windows, download and run Setup_CityEnergyAnalyst_2.20.exe. See the guide for more options.
2019-08-08 - 2.19 - #2216 Bugfix: Add script input validation for dashboard
2019-08-08 - 2.19 - #2225 I2224 optimization heating
2019-08-08 - 2.19 - #2230 fix occupancy
2019-08-05 - 2.19 - #2228 Bugfix: Calculate and save projected coordinate system
2019-08-05 - 2.19 - #2226 I2146 decentralized cooling @shanshanhsieh great! thanks!
2019-08-02 - 2.19 - #2222 I2120 fixing optimization cooling
2019-07-31 - 2.19 - #2160 2150 Feature: cea rename-building
> updating version, changelog and credits for v2.20

- cea/plots/base.py
@reyery this adds a button to turn on and off the legend. Quite handy since the legend is just huge in many plots. Maybe we can implement this in the front end rather than in the Back-end?
To test, just create any plot in CEA while using this brach
> fix legend

- cea/analysis/lca/mobility.py
- cea/api.py
- cea/config.py
- cea/inputlocator.py
- cea/scripts.py
- cea/scripts.yml
- cea/technologies/thermal_network/thermal_network_optimization.py
- cea/tests/cooling-case.yml
- cea/tests/heating-case.yml
This PR fixes some stuff with the cooling-case workflow. To test, run:
```
cea workflow --workflow cooling-case
```
from the CEA Console. The cooling-case does not run through due to issues #2256, #2255 and #2135 (which I can't test, because the workflow doesn't get that far)
Still, I think merging this now is a good idea. As it addresses all the issues with the workflow up to the decentralized script.
In addition (as per the PR title) it adds a cool feature: Lazy loading of the `cea.api` module. This will increase the startup-speed of the `cea dashboard` script as well as `cea workflow` by not loading cea script modules until they're actually used.
> FEATURE: lazy loading of cea.api module

- cea/tests/dodo.py
This PR is an attempt to solve the problem of the sensitivity analysis test randomly breaking - by fixing the random seed.
> set seed for sensitivity analysis test

- cea/interfaces/dashboard/plots/static/js/react-dashboard.js
This PR fixes #2314.
Bugfix
-
- Fix wrong function parameter when using set scenario function in dashboard
> Bugfix: Dashboard set scenario function not working

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
This is the result of the M2.22 sprint.
> Release 2.22

- cea/default.config
- cea/technologies/network_layout/main.py
- cea/technologies/network_layout/steiner_spanning_tree.py
This PR solves #2270 in fact other networks besides DH and DC are not fully supported for now
> fix to network layout script (EL is not implemented yet)

- cea/interfaces/dashboard/api/dashboard.py
- cea/interfaces/dashboard/api/inputs.py
- cea/interfaces/dashboard/api/project.py
- cea/interfaces/dashboard/api/tools.py
- cea/interfaces/dashboard/api/utils.py
- cea/interfaces/dashboard/inputs/static/js/store.js
- cea/interfaces/dashboard/inputs/static/js/table.js
- cea/interfaces/dashboard/inputs/templates/input_editor_electron.html
- cea/interfaces/dashboard/server/jobs.py
This PR add additional functions to the Flask server to enable the use of the upcoming electron version of the CEA.
The additions mainly include endpoints to create and manage project settings.
The pre-release version of the electron app can be downloaded here for testing. 
https://we.tl/t-5H3yJKhY08
> Project api for electron application

- cea/interfaces/dashboard/inputs/routes.py
- cea/utilities/standardize_coordinates.py
This fixes #2385 
To test, just try to import files with CEA from your own case study.
> fix coordinate system

- cea/demand/constants.py
- cea/demand/control_ventilation_systems.py
- cea/demand/schedule_maker/schedule_maker.py
- cea/scripts.yml
- cea/tests/dodo.py
- cea/tests/test_calc_thermal_loads.py
This PR solves #2399 - the Jenkins tests were failing and for good reason. I found some bugs and fixed them.
The reference-case-open.zip was also re-created to include the steps `data-helper` and `make-schedules`.
To test: run `cea test`.
> 2399 demand keyerror rhum max pc

- cea/datamanagement/schedule_helper.py
- cea/demand/schedule_maker/schedule_maker.py
- cea/demand/thermal_loads.py
- cea/inputlocator.py
- cea/scripts.yml
- cea/tests/test_schedules.py
- cea/utilities/schedule_reader.py
It seem the schedule maker was not working after the schedules were modified.
@lguilhermers chek and let me know when to merge
> fix to schedule maker

- cea/tests/trace_inputlocator.py
The `trace-inputlocator` tool, used to source data for the `schemas.yml` file, has a bug in it that makes it fail for locator methods that return a folder instead of a file. I found this out when trying to run the decentralized and optimization scripts.
This PR addresses that issue. To test, run `cea trace-inputlocator --scripts decentralized, optimization`
> BUGFIX: Handle folder locator methods in TraceInputLocator

- cea/interfaces/dashboard/api/inputs.py
- cea/interfaces/dashboard/server/__init__.py
This PR fixes endpoints for the react version of  _input-editor_ in the electron application and fixes #2424
> Update input api

- CHANGELOG.md
- CREDITS.md
- MANIFEST.in
- cea/__init__.py
- cea/demand/schedule_maker/schedule_maker.py
- cea/interfaces/cli/cli.py
- cea/plots/supply_system/supply_system_map.py
- docs/modules/cea.plots.thermal_networks.rst
- docs/modules/cea.utilities.rst
see https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v2.25
> Release 2.25

- cea/interfaces/dashboard/plots/routes.py
- cea/interfaces/dashboard/plots/templates/plot.html
- cea/plots/supply_system/map_div.html
- cea/plots/thermal_networks/network_plot.html
This PR resolves #2104 
Changes
-
- Update `plot.html` to only include plot div and required dependencies
GUI build can be found here: https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/10
_**Note:** Might need to consider removing some code of the previous web interface since it is still there_
> Open plot in new window

- .gitignore
- cea/demand/demand_main.py
- cea/optimization/master/cost_model.py
- cea/optimization/master/evaluation.py
- cea/optimization/optimization_main.py
- cea/optimization/preprocessing/decentralized_building_main.py
- cea/optimization/preprocessing/decentralized_buildings_cooling.py
- cea/optimization/preprocessing/decentralized_buildings_heating.py
- cea/optimization/preprocessing/processheat.py
- cea/optimization/prices.py
- cea/optimization/slave/cooling_main.py
- cea/scripts.yml
- cea/technologies/boiler.py
- cea/technologies/burner.py
- cea/technologies/chiller_absorption.py
- cea/technologies/cogeneration.py
- cea/technologies/heatpumps.py
- cea/technologies/supply_systems_database.py
- cea/technologies/thermal_network/thermal_network_costs.py
- cea/technologies/thermal_network/thermal_network_optimization.py
This PR addresses #2493 - it includes speed optimizations to the decentralized script, focussing on the heating case this time. The cooling case was looked at in a previous PR but this one has some optimizations for that too.
Key strategies:
- minimize reading of Excel files over and over again. This is a big one! The `locator.get_supply_systems_database()` file was being read multiple times in loops and also for separate worksheets. The class `cea.technologies.supply_systems_database.SupplySystemsDatabase` provides access to the worksheets as Dataframes - and also caches reading this (read-only) file (`supply_systems.xls`) by locator so that multiple instantiations for the same locator won't trigger a re-reading of the database. At the same time, care was taken to pass this object around …
> 2493 decentralized optimization

- cea/optimization/slave/electricity_main.py
Fixes issue #2527, due to which optimization for _both_ heating _and_cooling networks did not work.
> Fix incorrect locator method

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
This is the result of the M2.29 sprint. We worked mainly on fixing bugs and speed optimizations for the decentralized optimization script.
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_2.29.0.exe. [See the guide for more options](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up).
2020-01-23 - 2.28.1 - #2526 Fix COOLROOM bug in thermal networks
2020-01-23 - 2.28.1 - #2530 updated schemas.yml with trace-inputlocator output
2020-01-23 - 2.28.1 - #2532 fixed workflow and also bug in supply_systems.xls
2020-01-21 - 2.28.1 - #2528 Fix incorrect locator method @martin-mosteiro great catch!
2020-01-20 - 2.28.1 - #2522 2493 decentralized optimization. Tested with the centralized optimization too. …
> Release 2.29

- cea/default.config
- cea/optimization/master/crossover.py
- cea/optimization/master/evaluation.py
- cea/optimization/master/generation.py
- cea/optimization/master/master_main.py
- cea/optimization/master/master_to_slave.py
- cea/optimization/master/mutations.py
- cea/optimization/master/validation.py
- cea/optimization/optimization_main.py
- cea/optimization/slave/cooling_main.py
- cea/optimization/slave/heating_main.py
- cea/optimization/slave/natural_gas_main.py
- cea/optimization/slave_data.py
This solves issues #2534 and #2373, adding great functionality for our optimization users.
To test, just run the optimization algorithm for any case study and for a couple of generations, 10 individuals will do. Then create a few supply systems' plots.
> I2534 opt technologies

- cea/plots/optimization/Investment_costs.py
- cea/plots/optimization/annual_costs.py
- cea/plots/optimization/annual_emissions.py
@reyery mind testing this for me?
Just run the "annual emissions" and " annual costs plots" the results should be sorted.
> I2538 sorting plots

- cea/analysis/costs/system_costs.py
This fixes #2600 @daren-thomas here is the solution to your issue. Mind also cleaning up the milestones? i.e., closing the non-active ones? thanks!
> fix to systems costs

- cea/interfaces/dashboard/api/inputs.py
- cea/plots/supply_system/a_supply_system_map.py
- cea/technologies/supply_systems_database.py
This PR fixes some bugs for displaying supply network layouts in maps.
> Supply system bugfixes

- cea/inputlocator.py
@daren-thomas this should fix #2608
> Fix to decentralized optimization script

- cea/interfaces/dashboard/api/databases.py
- cea/plots/supply_system/a_supply_system_map.py
- cea/schemas.yml
This PR updates `schemas.yml` and allow GUI (https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/17) to do lookup for choice types.
> Database editor choice type

- bin/ceatest.bat
- bin/ceatestall.bat
- docs/installing-the-jenkins.rst
Master isn't building and I'm trying to find out why. This PR tries to separate the python environments used for the two Jenkins items.
> Jenkins fix merge to master

- cea/optimization/distribution/network_optimization_features.py
- cea/optimization/master/cost_model.py
- cea/optimization/slave/electricity_main.py
This solves #2621 
The problem had to do with passing series and sometimes passing arrays. Now it will always pass arrays. The problem should be solved now.
to test:
- run a few of the optimization routine. 
@daren-thomas mind taking a look at this PR? thanks!
> 2621 optimization fix

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
This PR is a small update to Release 3.0: After merging #2652, the GUI needs to be updated.
> Release 3.0.2

- cea/plots/optimization/__init__.py
- cea/plots/optimization/a_pareto_curve.py
- cea/plots/optimization/c_annual_costs.py
- cea/plots/optimization/d_annual_emissions.py
- cea/plots/optimization/e_Investment_costs.py
This PR resolves #2647 by renaming the optimization plot titles to better reflect what they are showing.
> Rename optimization plot titiles

- cea/demand/demand_main.py
- cea/demand/schedule_maker/schedule_maker.py
- cea/resources/radiation_daysim/daysim_main.py
- cea/tests/create_unittest_data.py
- cea/tests/test_calc_thermal_loads.py
- cea/tests/test_schedules.py
- cea/utilities/date.py
- cea/utilities/epwreader.py
- cea/utilities/solar_equations.py
This PR fixes #2645 by removing the leap day when reading the weather file and also removing it from the radiation output data.
> Remove leap day from weather data

- cea/demand/thermal_loads.py
The elaborate heatpump model for the electricity load calculations of space cooling was replaced by a simplified based on the system efficiency from the database. This adds consistency when comparing against results for District cooling and allows to distinguish between different building scale cooling technologies.
> extended system efficiency calculation to all building scale cooling systems

- cea/demand/demand_main.py
- cea/plots/optimization/c_annual_costs.py
- cea/tests/test_check_for_radiation_input_in_demand_script.py
- cea/utilities/epwreader.py
This fixes the bug with **epwreader** due to a missing variable `result`. This also adds normalization calculation to **Annual Cost** plot that was missing.
> Fix epwreader

- cea/plots/demand/comfort_chart.py
fixes wrong `log` spotted by user @compostable
> fixes issue 2073

- cea/schemas.yml
this provides a restriction to #2670 @rey mind checking if some of these restrictions are actually happening one way or another. it is surprising that the user was able to run CEA since the restriction in cea.datamanagement.data_verfication should not have allowed for this
> CEA cannot work with only underground structures

- cea/analysis/multicriteria/main.py
- cea/optimization/master/master_main.py
- cea/optimization/preprocessing/decentralized_buildings_cooling.py
- cea/optimization/preprocessing/decentralized_buildings_heating.py
- cea/schemas.yml
This solves #2712, #2713, and #2711 @shanshanhsieh mind testing? thanks!
> Remove "Unnamed: 0" columns in output files of optimization, decentralized and mulit-criteria-analysis scripts

- CHANGELOG.md
- CREDITS.md
- cea/__init__.py
This is the result of the M3.3 sprint. The detailed thermal-networks model now runs 25% faster. We are one step further to unifying all schema information (removal of `inputs.yml`) and cleaned up columns in output files. Thank you @compostable for spotting error #2703 - fixed. Detailed and simplified thermal-networks models now produce (roughly) the same output format and the plots will now work with both outputs.
To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_3.3.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.3.0/Setup_CityEnergyAnalyst_3.3.0.exe). See [the installation guide](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up) for more options. …
> release-3.3.0

- cea/config.py
- cea/resources/radiation_daysim/radiation_main.py
- cea/schemas.py
- cea/schemas.yml
- cea/technologies/thermal_network/thermal_network.py
- cea/workflows/cooling-system-current-scenario.yml
- cea/workflows/heating-system-current-scenario.yml
`schemas.yml` now does not contain any "Unnamed: 0" files anymore. To test: run `cea test --workflow slow` and also search schemas.yml for "Unnamed"
> 2667 clean up unnamed in schemas yml

- cea/schemas.yml
This solves #2757, I am not sure how to indicate integers in the schemas, maybe @daren-thomas can check and correct directly if the way i did it is not correct? thanks!
> Fixing electro-mobility documentation

- cea/schemas.py
- cea/schemas.yml
This PR resolves #2743 based on ranges as stated below.
> 
> 
>     * components:conversion:PV: PV_a1, PV_a2, PV_a4 : [+0.1,-0.1]
> 
>     * components:conversion:Absorption_chiller: r_e, r_g, a_e, a_g: could be negative (no fixed bound)
> 
>     * components:conversion:HEX: a, d_p: could be negative (no fixed bound)
> 
>     * components:conversion:HP: e: could be negative (no fixed bound)
> 
>     * components:conversion:TES: e: could be negative (no fixed bound)
Testing:
- There should not be any errors in GUI database editor due to negative values in the respective databases.
> Update range values

- cea/analysis/costs/system_costs.py
- cea/analysis/lca/embodied.py
- cea/analysis/lca/operation.py
- cea/demand/demand_writers.py
- cea/technologies/solar/photovoltaic.py
- cea/technologies/solar/photovoltaic_thermal.py
- cea/technologies/solar/solar_collector.py
This is about Issues #2797 #2827  #2826 . 
This pull request fixes the empty columns in the outputs of demand, solar-collector, photovoltaic, emissions.
> Empty columns fixed

- cea/schemas.yml
this PR resolves #2825 
steps to test this issue:
1. open GUI
2. open Database Editor- Archetypes - Envelope Assmblies and check if it is possible to set the void_deck to other integers
> void_deck remove max: null and set type to int

- cea/datamanagement/zone_helper.py
this PR resolves #2953 
to test, use the dashboard to create new scenario in any location in europe
> 2953 zone helper

- cea/dev/build.py
- cea/interfaces/dashboard/api/project.py
- cea/plots/cache.py
- cea/resources/radiation_daysim/radiance.py
- cea/utilities/create_polygon.py
Add command that makes sure `conda-pack` is installed into script `cea-dev build`.
Change some `os.makedirs` to ignore if directory already exists
> Make sure conda-pack is installed when creating the installer

- cea/interfaces/dashboard/api/inputs.py
This PR fixes #2960
As mentioned here https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2960#issuecomment-833465018, adding the route back should fix this.
> Add missing database export endpoint

- cea/inputlocator.py
Fixes #3079 .
reimplemented changes from Jimeno's HotFix ("CEA needs a temp file per scenario. This should not change main functionality.")
I have tested with the district_cooling_system and district_heating_system workflows, as well as my own scenario and it seems to work without any additional changes. Please let me know if you spot any problem.
> redo commit eb298828dd2e22ea6437d96e4c84eaea422cc77e)

- cea/demand/thermal_loads.py
- cea/optimization/preprocessing/decentralized_buildings_heating.py
- cea/optimization/preprocessing/preprocessing_main.py
- cea/optimization/slave/seasonal_storage/design_operation.py
- cea/resources/geothermal.py
- cea/technologies/thermal_network/simplified_thermal_network.py
- cea/technologies/thermal_network/thermal_network.py
This PR resolves #3091 .
other changes includes:
- clean up docstrings in `thermal_networks.py`
- PEP8 formatting `thermal_networks.py`
- refactor `calc_ground_temperature`
- refactor `calc_aggregated_heat_conduction_coefficient`
**To test**, run `cea test --workflow slow` until completion.
> 3091 thermal network

- cea/demand/demand_writers.py
- cea/demand/thermal_loads.py
This PR resolves #3101.
To test:
- in `cea.config`, set `debug = true` 
- run `cea demand` for any project and see if the script completed successfully.
> set demand_writers to write temp file when debug=True

- cea/datamanagement/databases_verification.py
- cea/demand/demand_main.py
- cea/demand/electrical_loads.py
This PR resolves #3104 
To test, use the same case study provided in the issue and run demand calculation again.
> 3104 calc eauxf fw

- cea/demand/latent_loads.py
This solves #3121 .
To test: download the scenario mentioned in the issue above and test in master and in this branch.
Note: Even with the error gone, maybe would still be appropriate to look for the values being produced and see if they are making sense, but this is a bit beyond my capabilities and resources at the moment.
> changed exp solver to numpy

- cea/optimization/constants.py
- cea/optimization/distribution/network_optimization_features.py
- cea/optimization/lca_calculations.py
- cea/optimization/master/cost_model.py
- cea/optimization/master/crossover.py
- cea/optimization/master/evaluation.py
- cea/optimization/master/master_main.py
- cea/optimization/master/master_to_slave.py
- cea/optimization/master/validation.py
- cea/optimization/optimization_main.py
- cea/optimization/preprocessing/preprocessing_main.py
- cea/optimization/slave/cooling_main.py
- cea/optimization/slave/cooling_resource_activation.py
- cea/optimization/slave/daily_storage/load_leveling.py
- cea/optimization/slave_data.py
- cea/resources/water_body_potential.py
- cea/technologies/chiller_vapor_compression.py
- cea/technologies/cogeneration.py
- cea/technologies/substation.py
This is pure documentation and refactoring and should not change anything about the code. 
To test, ideally run the optimisation script with any scenario on the master branch first then with the activation of this branch. The output should be identical.
> Refactoring of optimization algorithm - Part I

- cea/demand/building_properties.py
There was only last commit to #3130 that didn't get pushed before merge. This commit avoids going through all buildings in `verify_hvac_system_combination`, instead only buildings that need mechanical HVAC but don't have mechanical HVAC are included.
> Finish #3124

- .github/workflows/main.yml
Runs `cea test --workflow slow` when commits are pushed to master
> Run tests when pushed to master

- cea/datamanagement/zone_helper.py
> Fix parsing years with numeric string

- cea/datamanagement/streets_helper.py
- cea/datamanagement/surroundings_helper.py
- cea/datamanagement/terrain_helper.py
- cea/datamanagement/zone_helper.py
This fixes the error described in issue #3211 .
To review:
1. Check code changes. (there are very few of them, so it should be fairly simple)
OR
2. Purposely change the CRS of one of the two .shp files right before running the terrain helper. See if the error still occurs.
> Handling potential CRS mismatch

- cea/interfaces/dashboard/frontend/__init__.py
Closes #3327
Run to test
```
cea dashboard --browser true
```
Non-browser version (GUI application) will not be updated
> Fix EV input validation in editor

- cea/utilities/epwreader.py
> Read weather file with encoding

- cea/default.config
This PR has unified the default settings.
> Unified default settings

- cea/workflows/ch_data_management.yml
- cea/workflows/ch_demand_forecasting.yml
- cea/workflows/ch_district_heating_network.yml
- cea/workflows/ch_energy_optimization.yml
- cea/workflows/ch_life_cycle_analysis.yml
- cea/workflows/ch_solar_potential.yml
- cea/workflows/sg_data_management.yml
- cea/workflows/sg_demand_forecasting.yml
- cea/workflows/sg_district_cooling_network.yml
- cea/workflows/sg_energy_optmization.yml
- cea/workflows/sg_life_cycle_analysis.yml
- cea/workflows/sg_solar_potential.yml
This PR includes 6 automated batch-processing options for Singapore(sg) and Zurich(ch).
They are data management, demand forecasting, district heating/cooling network, energy optimization, life cycle analysis, and solar potential.
All 12 options execute the series of necessary CEA scripts from the minimum CEA inputs (i.e. zone.shp, typology.dbf).
How to test?
1. Open CEA Console
2. Type the following and press Enter:
`cea workflow --workflow ch-data-management`
`cea workflow --workflow ch-demand-forecasting`
`cea workflow --workflow ch-district-heating-network`
`cea workflow --workflow ch-energy-optimization`
`cea workflow --workflow ch-life-cycle-analysis`
`cea workflow --workflow ch-solar-potential`
`cea workflow --workflow sg-data-management`
`cea workflow --workflow …
> Adding automated batch-processing options

- cea/datamanagement/__init__.py
- cea/plots/base.py
- cea/plots/optimization/a_pareto_curve.py
- cea/plugin.py
- environment.yml
- setup.py
This is in preparation of moving to using conda-lock for installations to avoid any problems with different python dependencies in the future.
> Clean conda dependencies

- .github/workflows/docker.yml
- Dockerfile
- conda-lock.yml
- environment.yml
> Automate docker image build

- .github/workflows/setup_build.yml
- cea/plots/base.py
- cea/resources/radiation/daysim.py
- setup/cityenergyanalyst.nsi
- setup/dashboard.bat
- setup/dependencies/cea-env.bat
> Fix Windows setup bugs and plots

- setup/cityenergyanalyst.nsi
> Always set default installation directory to Documents

- cea/interfaces/dashboard/api/inputs.py
> Update deprecated pandas append function

- .github/workflows/docker.yml
> Push Docker build to GitHub Container Registry

- cea/utilities/reporting.py
Updating Excel writer to work with the latest version of the `pandas` and `OpenpyxlWriter` libraries.
> Fixing oudated excel writer

- cea/resources/radiation/main.py
- cea/schemas.yml
- cea/scripts.yml
> updating a wrong term for trees helper

- cea/datamanagement/terrain_helper.py
- cea/resources/radiation/geometry_generator.py
- cea/resources/radiation/main.py
Consider tree bounds when creating terrain file using terrain helper and checking intersections during radiation.
> Consider tree bounds with terrain

- cea/demand/sensible_loads.py
- cea/utilities/epwreader.py
Fixes #3600
Fixes #3603 
We validate the .epw weather file now to ensure temperatures do not increase exponentially in some cases.
> Fix high internal temperatures during demand calculation

- cea/datamanagement/terrain_helper.py
- cea/default.config
> Fix terrain bounds error after using terrain-helper

- docs/installation/installation-on-docker.rst
- docs/installation/installation-on-macos.rst
- docs/installation/installation-on-windows-manual.rst
- docs/installation/installation-on-windows.rst
- docs/installation/installation.rst
I have updated the installation guide on CEA documentation.
> Update documentation 3.37.x

- cea/resources/radiation/main.py
- cea/resources/radiation/simplified/main.py
Fixes #3637
`radiation-simplified` was failing because the functions were not updated to handle tree shading.
> Fix radiation simplified

- cea/config.py
- cea/default.config
Prevents empty string from resolving into current working directory
> Allow project root to be nullable

- cea/datamanagement/schedule_helper.py
> Fixing schedule-helper that hard-coded hotel use type to be in the database

- Dockerfile
> Fix Dockerfile micromamba

- cea/import_export/result_summary.py
run summary feature and check pv/analytics
> Merge advanced analytics into summary
