architecture-building-systems/CityEnergyAnalyst

cea/demand.py, cea/globalvar.py, cea/graphs.py, cea/toolbox.py
Using this technique, it is possible to change the `print` statements in the scripts to `gv.log` and they will print just the same.
BUT: When run from the toolbox, the `log` method can be replaced with the new `add_message` which will use `arcpy.AddMessage` instead: voila! We now have logging in arcgis for long-running tasks!
=> added `log` method to `GlobalVariables`

.gitignore, cea/demand/sensible_loads.py, cea/demand/thermal_loads.py, tests/test_sensible_loads.py
see the discussion on the issue for more information
=> fixes #358

cea/GUI/demand_tool.py, cea/demand/demand_main.py, tests/test_calc_thermal_loads.py, tests/test_check_for_radiation_input_in_demand_script.py
How to test: The Jenkins will run the unit test to check the part of the demand script raises the ValueError - but you could run a demand simulation manually (with command line interface) for a scenario without radiation files to check this...
In ArcGIS, run the demand tool for a scenario without radiation files. It should not let you start the simulation, but instead provide an error message ("No radiation data found for scenario. Run radiation script first.")
=> 222 check for radiation input in demand script

cea/GUI/scenario_plots_tool.py
A simple 'import arcpy' statement was missing from the Scenario Plots file. Added it to make it run. It is necessary for this to be reviewed soon as we need to present on 24-02-2017 (Friday).
=> Fix import arcpy error in ScenarioPlotsTool

docs/installation-on-euler.rst
As discussed with @daren-thomas, the file path for the weather in the example did not match the folder structure created when cloning from GitHub.
=> Wrong filepath for the weather in the final example

euler/README.md
Consistently uses `.\cea\databases\CH\Weather\...` as a file path, but that doesn't match the actual folder structure of the CEA (should be and has been corrected to `.\cea\databases\weather\...`)
=> Correcting weather file path in the euler readme

cea/demand/thermal_loads.py
If there is no heating system, the building can't be heated. So 'Af' and 'Hs' are set to zero and a warning is printed out.
This pull request replaces PR #561, which was a mess. This new PR is clean and simple.
=> i560 RC model inconsistent inputes - replaces PR #561 

cea/interfaces/arcgis/CityEnergyAnalyst.py, docs/installation-guide.rst
- adds `ephem` to the conda install in the installation guide (readthedocs)
- tested with a portable miniconda from scratch (need to add the root of miniconda installation to PATH as well as the Scripts folder)
- updated arcgis interface to add the required folders to PATH
=> fix environment for running fiona.ogrext - this should fix a lot of installation problems

cea/resources/radiation_daysim/create_gml.py
correct conversion of string to integer if dbf file is defined as double
accidentally
=> correct conversion of string to integer if dbf file is defined as double accidentally

cea/__init__.py, cea/interfaces/arcgis/install_toolbox.py, cea/resources/radiation_arcgis/radiation.py
@JIMENOFONSECA includes changes necessary to get CEA to run with 64bit Python in the ArcGIS environment for the HIL E65 computerroom. Also, upgrade to ArcGIS Desktop 10.5 and 64bit background processing.
=> 731 port cea to arcgis 10 5 for computerroom hil e65

cea/optimization/constants.py, cea/optimization/master/summarize_network.py, cea/optimization/slave/least_cost.py
While running optimization for a higher number of generations, there is a chance where the COP becomes negative and which in turn leads to negative costs. This was being caused because of the default values of temperatures in networks (in Kelvin) being '0'. Now I changed it to '273' (which is the default 0 in degree C). This fixed the issue of having negative costs and emissions. Also, while I was at it, fixed few loops where the denominator can become '0' and thus raising Nan's. These observations were not found prior because they occur once or twice in 1000 samples.
=> steps to avoid Nan's and 0K temperature values

cea/interfaces/arcgis/CityEnergyAnalyst.py
This PR is connected to issue #963 
The category name is changed from "Dynamic Supply Systems" to "Energy Supply Technologies"
It currently contains: Photovoltaic Panels, Solar Collector Panels, and PVT Panels
=> Renaming tools for ArcGIS

cea/demand/building_properties.py
Building names in building_properties.py were being listed by using `envelope.index` instead of the appropriate input locator (`locator.get_zone_building_names()`). This created problems in certain cases, so it needed to be fixed.
=> Use appropriate InputLocator to list building names

cea/default.config, cea/demand/demand_writers.py
The variables `mcpcsf_kWperC` and `mcphsf_kWperC` reintroduced to demand output `.csv`.
Valid choices updated in the `default.config` file.
=> I1128 fix demand output

docs/installation-guide-ubuntu.rst, docs/installation-on-windows.rst
I have updated the clone process of github repos to operate through the github desktop app rather than conda prompt. this will setup github desktop as well as clone the repos.
i have also updated pycharm set up slightly to reflect new interface and have updated path via cmd to avoid any confusion.
finally i have changed the link for pycharm from anaconda home page to jetbrains dl address for both ubuntu and windows install docs.
=> Minor changes to Windows install

cea/config.py, cea/default.config, cea/interfaces/arcgis/arcgishelper.py
This PR updates the `default.config` file to use `FileParameter` instead of `PathParameter` and `StringParameter` for the files used by `cea create-new-project`. The `cea/config.py` and `cea/interfaces/arcgis/arcgishelper.py` files were updated to allow `FileParameter` parameters to be "nullable" / optional.
Testing would ideally include trying out more than just this tool - especially other tools that use `FileParameter`.
=> 1225 - Fix arcgis interface folder path pop-up

cea/technologies/solar/photovoltaic.py, cea/utilities/solar_equations.py
this PR resolves #1278  
the `degrees` and `radians` functions from the math library is properly imported from the math library now 
to test, run `photovoltac.py` and `photovoltaic_thermal.py` with the reference case, or any test case you are running currently.
=> import all functions from math library

cea/demand/demand_writers.py, cea/plots/demand/comfort_chart.py
- removed unnecessary outputs from total demands (used only for building level energy balance plot)
- fixed comfort plot
fixes #1192 #1286
=> i1192-i1286-clean-total-demands-fixed-comfort-plot

cea/interfaces/arcgis/arcgishelper.py
To test:
- `cea install-toolbox`
- rename the scenario in your config file (like, add `.bak` to the end or something)
- refresh the `CityEnergyAnalyst.pyt`
Expect the toolbox to now work without an error.
Oh, BTW, while I was at it i did some profiling to make sure it's not our fault that loading the toolbox takes so long. It's not. It's in the arcpy stuff.
=> fixes #1346 - Plot tool doesn't work on ArcScene

cea/config.py, cea/default.config, cea/interfaces/arcgis/CityEnergyAnalyst.py, cea/interfaces/arcgis/install_toolbox.py, cea/interfaces/arcgis/test.pyt, cea/interfaces/cli/cli.config, cea/plots/comparisons/main.py
Fixes #1321 - text copied from there:
I ended up fixing it with a generalization of how the SubfoldersParameter works (the parent is now a folder with references substituted, instead of a link to a property itself). To test:
- `cea install-toolbox`
- run the plots tool
- changing the scenario folder will change the list of scenarios to choose from for comparison
NOTE: `cea install-toolbox --debug true` will install a `test.pyt` as well, that contains just the plots tool. a bit quicker to open. BUT: check with the `CityEnergyAnalyst.pyt`, as that is the one we need to test.
=> 1321 arcgis interface plotting of scenario comparison not interactive

cea/plots/demand/comfort_chart.py, cea/plots/demand/main.py
hey @daren-thomas 
while removing the creation of a new `config` and `locator` and instead passing them down from the main function, I realized that the plot got broken by someone changing the input data types.
I fixed this immediately by converting it to the expected data type.
Would be nice if you could take a look.
Testing by plotting one single building.
```
[plots]
scenarios =
buildings = B006
categories = energy_demand
generations = 
individual =
network-type =
network-names =
```
=> fixed comfort plot: pass down locator and config, fix type

cea/interfaces/cli/cli.config
To test:
run `cea install-toolbox`, restart ArcGIS, check the `data-helper` tool. you should now be able to choose the region from the dropdown.
=> adding region to data-helper tool

cea/config.py, cea/interfaces/arcgis/CityEnergyAnalyst.py, cea/interfaces/arcgis/arcgishelper.py, cea/interfaces/arcgis/test.pyt, cea/interfaces/cli/cli.config, cea/interfaces/cli/cli.py
This fixes a few annoying things that cropped up in the test-run of the executive course. Including:
- saving parameter choices to the config file between invocations of the interface
- (figuring out how to determine when a user made a change and when the dialog was being shown for the first time was a bit of a challenge btw)
- adding the "region" dropdown to the demand calculation. it was there before, but somehow got removed?
=> 1390 arcgis interface should update the config file

cea/resources/radiation_daysim/daysim_main.py
When creating the JSON of radiation results we were using the results for building 2 for ALL buildings except builiding 1 due to not counting up the index.
=> IMPORTANT SOLAR RADIATION FIX!

bin/ceajenkins.py, docs/installing-the-jenkins.rst
The Jenkins is not working correctly. This update switches the tunneling solution used to use ngrok.io (paid) instead of localtunnel.me (free).
=> update ceajenkins.py to use ngrok.io instead of localtunnel.me

environment.yml
hdf5 1.10.2 seems to be a problem for now... This is a proposed fix to the `environment.yml` file.
=> Urgent fix for a h5py error that just showed up (failing jenkins tests)

cea/default.config, cea/demand/demand_main.py, cea/technologies/thermal_network/thermal_network_matrix.py, cea/utilities/number_of_processes.py
Introduces limiting function to the total amount of processes used in multiprocessing, default is set to leave on CPU open. The maximum number of processes is now a user input into the config file.
=> Limit number of processes of multiprocessing

cea/default.config, cea/optimization/master/master_main.py
This PR allows running optimization from a checkpoint. This can be used to continue from any stopped checkpoint. The only constraint is that it needs have the same initial individuals as the checkpoint.
=> fixes to run from intermittent generations

cea/demand/refrigeration_loads.py, cea/demand/thermal_loads.py
This PR solves four different minor issues:
1) since COOLROOM building types have Hs=0, the electricity demand for refrigeration was not calculated for this building type (which is the only type that has refrigeration by default)
2) the wrong number of arguments was passed to the function `refrigeration_loads.calc_Qcre_sys`
3) the wrong number of arguments was passed to the function `refrigeration_loads.calc_Qref`
4) the wrong label was used for a column in the DataFrame `energy_source` in `refrigeration_loads.calc_Qref`
=> I1542 qcre takes 3 arguments

cea/demand/thermal_loads.py
This PR fixes issue #1585. The number of inputs passed to `calc_Qcdataf` in `thermal_loads.py` was wrong, so the demand calculation for buildings including data centers failed.
=> Correct number of inputs to calc_Qcdataf

cea/interfaces/cli/cli.py, cea/scripts.py, cea/utilities/dbf.py
implements #1631. To test, run the commands `cea --help data-helper` or `cea-config data-helper` (or any other script the cea implements).
Also, the default values are shown when running scripts via the `cea` command.
=> Show default values for tool parameters in cea and cea-config

docs/installation-on-windows.rst
I changed the disclaimer to occur at the start rather than the end (makes more sense).
Omitted Anaconda2 (just Miniconda2) as an install option to reduce time and uncertainty.
Created space and time estimations for the installation section to advise new comers.
=> updated the install instructions to include size and time

CREDITS.md, cea/__init__.py, cea/config.py, cea/datamanagement/data_helper.py, cea/interfaces/arcgis/arcgishelper.py, cea/scripts.yml, setup.py
implements #1710 (Make release 2.9.1) but also includes some fixes:
- #1755 (cea unusable if C:\reference-case-open\baseline doesn't exist))
- #1771 cea env needs to include mock (to test: new environment, run `cd docs; make html`)
=> Release 2.9.2

cea/demand/metamodel/nn_generator/input_matrix.py, cea/demand/metamodel/nn_generator/input_prepare.py, cea/inputlocator.py, cea/optimization/master/normalization.py, cea/optimization/slave/seasonal_storage/design_operation.py, cea/optimization/slave_data.py, cea/optimization/supportFn.py, cea/plots/old/graphs_optimization.py, cea/plots/old/sensitivity_demand_graphs.py, cea/resources/natural_gas.py, cea/technologies/boiler.py, cea/technologies/burner.py, cea/technologies/chiller_absorption.py, cea/technologies/chiller_vapor_compression.py, cea/technologies/direct_expansion_units.py, cea/technologies/furnace.py, cea/technologies/heatpumps.py, cea/tests/create_unittest_data.py, legacy/thermal_networks/thermal_network.py
This PR is a smal step towards resolving #753 - I removed some low hanging fruit like:
- removed all instances of `gv` that were not used (greyed out in PyCharm)
- removed `:param:` mentions of `gv` where the function signature changed (not exhaustive, just those I ran into)
- removed / renamed `gV` to `gv` to make future finding of `gv` easier.
There are still usages. If the Jenkins likes this PR, we can merge it and then do the next step:
I suggest @gabriel-happle addresses the usage of `gv.start_date` in a separate PR based on this one merged to master.
=> 753 remove low hanging fruit global variables

cea/config.py, cea/interfaces/dashboard/dashboard.py, cea/interfaces/dashboard/plots/routes.py, cea/interfaces/dashboard/project/routes.py, cea/plots/__init__.py, cea/plots/base.py, cea/plots/cache.py, cea/plots/categories.py, cea/plots/demand/__init__.py, cea/plots/demand/comfort_chart.py, cea/plots/demand/energy_balance.py, cea/plots/demand/energy_demand.py, cea/plots/demand/energy_supply.py, cea/plots/demand/energy_supply_intensity.py, cea/plots/demand/energy_use_intensity.py, cea/plots/demand/heating_reset_schedule.py, cea/plots/demand/load_curve.py, cea/plots/demand/load_curve_supply.py, cea/plots/demand/load_duration_curve.py, cea/plots/demand/load_duration_curve_supply.py, cea/plots/demand/peak_load.py, cea/plots/demand/peak_load_supply.py, cea/plots/optimization/__init__.py, cea/plots/optimization/centralized_costs_per_generation_unit.py, cea/plots/optimization/cost_analysis_centralized_system.py, cea/plots/optimization/pareto_capacity_installed.py, cea/plots/optimization/pareto_curve.py
This pull request implements a caching system for plots and their data (see `cea.plots.cache.PlotCache`)
Data used by plots can be cached using `PlotCache.lookup(...)` to the folder `$project/.cache/<category_name>/<data_or_plot_name>/`. The filename for the cached data is made by using a md5 hash of the sorted parameter dictionary. This guarantees unique names for the same data with different parameters.
Each plot lists it's `input_files` in the `__init__` method. The timestamps of these files are compared with the cached data and if a newer one is found, the data is re-calculated.
The `<div/>` version of the plots are cached using the same mechanism to speed up the display of the dashboard.
=> Plot cache for dashboard

cea/interfaces/dashboard/landing/static/landing_map.js, cea/interfaces/dashboard/landing/templates/project_map.html
This PR resolves #1934. It separates the coordinates input in the map tool to two separate latitude and longitude inputs.
=> Split coordinates to lat lon input

cea/interfaces/dashboard/base/templates/site_template/sidebar.html
This PR resolves #1938. The sidebar navigation links are relocated accordingly, with project management at the top and dashboard at the bottom. Project navigation link is moved to the settings icon at the bottom left. Icon for tools is also changed to not look like the settings icon.
=> 1938 relocate sidepanel links

setup/cityenergyanalyst.nsi
This is just a tiny PR that changes the location we use to retrieve the CEA python environment (used to be Daren's private polybox, moved to using the binary attachement system of GitHub)
=> Update installer to retrieve CEA environment from a known location

cea/datamanagement/data_helper.py, cea/interfaces/dashboard/inputs/routes.py
This PR fixes #1964. Users should now be able to edit and save any updates to the input databases from the dashboard.
To test, try to update and save any changes to any of the input databases from the dashboard.
=> Retain dtypes of dataframe columns

cea/interfaces/grasshopper/install_grasshopper.py
A tiny Bugfix for the `cea install-grasshopper` command: I did a `git log --full-history -- cea/concept_parameters.py` according to [this answer on stackoverflow](https://stackoverflow.com/questions/6839398/find-when-a-file-was-deleted-in-git) - I'm pretty sure that file never ever existed and explains the bug @shizhongming is having with https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1896#issuecomment-493307814
@shizhongming would you mind testing this to see if it solves the problem? thank you!
=> Fix for cea install-grasshopper

cea/api.py, cea/config.py, cea/datamanagement/district_geometry_helper.py, cea/scripts.yml, docs/conf.py, docs/how-are-schedules-defined.rst, docs/how-to-run-thermal-network-optimization.rst, docs/how-to-set-up-nsis.rst, docs/installation-guide-ubuntu.rst, docs/script-input-outputs.rst
Some fixes to the documentation to remove sphinx warnings. 
I had to stop after this error - see issue #1974:
```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst\docs (2019.05.17-some-documentation-fixes -> origin)
λ make-warnings.bat
REM @ECHO OFF
pushd C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst\docs\
REM Run Sphinx and break on first error / warning
sphinx-build -b html -j 4 -Q -W . _build
Warning, treated as error:
autodoc: failed to import module u'planning_and_operation_batch_run' from module u'cea.optimization.flexibility_model.mpc_district'; the following exception was raised:
No module named concept
popd
```
=> 2019.05.17 some documentation fixes

setup/cityenergyanalyst.nsi
This PR addresses #1987 - `cea test` was not running through on a fresh install. The issue has to do with the QT_PLUGIN_PATH. The solution was to update the `CityEnergyAnalyst\Dependencies\Python\qt.conf` file to point to the proper paths.
This new installer does just that. It can be tested here: https://www.dropbox.com/s/cgf9jkcaikzo618/Setup_CityEnergyAnalyst_2.14.exe?dl=0
@gabriel-happle would you mind testing it please?
Steps:
- download installer from link above
- install (doesn't really matter which type)
- open CEA Console
- run `cea test`
- expect it to complete
Once this is merged, we can update the binary in the release 2.14.
=> 1987 fix qt conf for installer

cea/plots/base.py, cea/plots/life_cycle/__init__.py, cea/plots/solar_technology_potentials/__init__.py, cea/plots/solar_technology_potentials/all_tech_hourly_curve.py, cea/plots/solar_technology_potentials/all_tech_yearly.py, cea/plots/solar_technology_potentials/main.py, cea/plots/solar_technology_potentials/pv_monthly.py, cea/plots/solar_technology_potentials/pvt_monthly.py, cea/plots/solar_technology_potentials/sc_monthly.py
This PR implements #1983 (Add solar technologies plots to the dashboard).
To test it, run the Dashboard and add all the plots from the "Solar technology potentials" category. Try out different settings.
The plot "PV/SC/PVT Potential per Building for District" is not as nice as it could be. This is a one-to-one translation from how it was originally generated. I think the "instructions" part are in the way. I will create a separate issue to fix that.
=> 1983 add solar technologies plots to the dashboard

cea/interfaces/grasshopper/ghhelper.py, cea/interfaces/grasshopper/install_grasshopper.py
The PR fixes #1761, which ensures that the `config.py` is copied over to the destination folder for `Grasshopper` to work.
=> 1761 fix grasshopper installer script

cea/default.config
Variable network-type was described as follows: "type of network used, based on the region, for Switzerland it is DH, for Singapore it is DC". This is not a good description of what the variable means.
1. The point is to describe what DH and DC means (that is, district heating and district cooling), not to associate them to specific countries.
2. The description is inaccurate: what if you are modeling a district cooling network in Switzerland?
3. What if your case study is neither in Singapore nor in Switzerland?
This PR changes the descriptions to something more explanatory:
- For `cea.config.thermal_network`: `network-type.help = Type of network to be simulated, either DH (district heating) or DC (district cooling)`
- For `cea.config.thermal_network_optimization`: `network-type.help = …
=> Improve description of variable `network-type`

cea/technologies/thermal_network/thermal_network.py, cea/technologies/thermal_network/thermal_network_optimization.py, setup.py
This PR changes a few lines in `thermal_network.py` so that whether the representative week per month method is defined by the `thermal_network` section of the config file, not `thermal_network_optimization`. 
Up until now the variable was called as `config.thermal_network_optimization.use_representative_week_per_month`, so whether the representative week method is used or not was defined not by the thermal-network section of the config file, but by the thermal-network-optimization section (i.e., when running thermal network simulation the optimization configuration overrides the simulation configuration).
=> Thermal network simulation config file

cea/interfaces/dashboard/landing/routes.py
This PR fixes #1996. Dashboard will check if the project path exists before setting it as the default value.
This also fixes error of using scenario name instead of scenario path for `inputlocator`
=> Bugfix: Remove 'Open project' default value if path does not exists.

cea/datamanagement/data_helper.py
This PR fixes #2073. It changes the behavior of the column validation found in `data_helper`, introduced in #2034, to also ignore the `REFERENCE` column if it is in `occupancy`.
=> Bugfix: Ignore REFERENCE when checking columns in data_helper

cea/datamanagement/terrain_helper.py
This PR fixes #2014. Made sure that the difference between the boundary `max` and boundary `min` divided by `grid_size` would generate a whole number, so casting it into an `int` would not lose any precision.
=> Bugfix: Fix terrain boundary caused by rounding error

cea/api.py
This PR fixes #1968 by adding a script completion message to all tools run by the Dashboard (and other uses of `cea.api`) along with the total time in seconds used by the script.
To test, run a tool in the Dashboard. Example output:
```
City Energy Analyst version 2.16
Running `cea operation-costs` with the following parameters:
- general:scenario = C:\Users\daren-thomas\Dropbox\tmp\reference-case-cooling\baseline
(default: C:\reference-case-open\baseline)
Running operation-costs with scenario = C:\Users\daren-thomas\Dropbox\tmp\reference-case-cooling\baseline
---------------------------------------
Script completed. Execution time: 0.18s
```
=> add message for script completion to dashboard

cea/api.py, cea/config.py, cea/default.config, cea/interfaces/dashboard/tools/routes.py, cea/interfaces/dashboard/tools/static/tools.js, cea/technologies/thermal_network/thermal_network.py
This PR fixes #2026 which noticed that tool parameters were being ignored for the `thermal-network` script when run from the Dashboard without first clicking on "Save Configuration".
While at it, I also added the fix from #1814 to the `thermal-network` script so we can see live output of  the script in the Dashboard window.
=> 2026 dashboard tools parameters ignored

bin/trace-inputlocator.bat, cea/config.py
This PR addresses #2008 - to reproduce the bug:
- open `cea.config` file
- set `demand:buildings` to a value like... `X, Y, Z`
- run dashboard, navigate to a project (I used output of `cooling-case-workflow`)
- open demand tool - buggy behavior shows up.
With this PR, if the contents of the config file for any derivative of `MultiChoiceParameter` has an in valid choice, that choice is ignored.
=> 2008 demand tool not working when non existing building selected

cea/interfaces/dashboard/tools/routes.py, cea/interfaces/dashboard/tools/static/tools.css, cea/interfaces/dashboard/tools/templates/tool.html
This PR resolves #1979, by adding collapsible panels that group input fields based on their parameter category. 
To test this, try these on tools with parameters with categories. Changing settings of parameters in these panels should also be reflected when running the scripts.
=> Add collapsible fields for tools

cea/datamanagement/district_geometry_helper.py, cea/datamanagement/zone_helper.py
This PR solves #2107 and solves #2091.
There was a mistake in the `if` conditions of the `zone-helper` and `district-helper` where the `REFERENCE` column is only created if the user leaves `height_ag` and `floors_ag` blank.
=> Bugfix: REFERENCE column is not added when user changes parameters in zone and district helper

cea/interfaces/dashboard/landing/routes.py
This PR resolves #2088.
Scenario images will now be updated in the `project overview` if the `zone` file is updated, by comparing their modification timestamp. Images of deleted/non-existing scenarios in the `.cache` folder will also be deleted.
=> Bugfix: Update scenario image if zone file is modified

cea/interfaces/dashboard/inputs/static/js/table.js
This PR resolves #2130.
Bugfix
---
- Allow for decimal values to be entered in number inputs in the edit selection menu
- Add validation to reject negative values
=> Bugfix: Allow decimal values for number inputs

cea/interfaces/arcgis/arcgishelper.py, cea/interfaces/arcgis/install_toolbox.py
This issue addresses #2095 in a minimal fashion: The toolbox now loads, but there are three tools that don't currently work:
- MpcBuildingTool
- MpcDistrictTool
- PlotsTool
Since we've dropped official support for this interface, I believe it's ok to leave those three as is and maybe address it later in a separate issue.
To test this PR:
- run `cea install-arcgis` from CEA Console
- open ArcScene and check "My Toolboxes/City Energy Analyst.pyt"
- run some tools
=> 2095 FIXED "ArcGIS interface installation does not work anymore"

cea/interfaces/dashboard/plots/static/js/dashboard-plots.js, cea/interfaces/dashboard/plots/templates/layout/layout_container.html, cea/interfaces/dashboard/plots/templates/layout/row_layout.html, cea/interfaces/dashboard/plots/templates/plot_widget_macros.html
This PR resolves #2171, resolves #2172, resolves #2173.
Fixes
---
- Instead of using browser window popups for the plot tables, they appear as draggable modals within the browser.
- Plots without tables will not show the table button in their titlebar
=> Fix: Dashboard popup tables

cea/datamanagement/terrain_helper.py, cea/datamanagement/zone_helper.py, cea/inputlocator.py, cea/interfaces/dashboard/landing/routes.py
How to test:
- create a new project folder, with an empty scenario folder inside
- start CEA Dashboard
- choose "Open Project" and select the project folder
- in the project overview, choose the empty scenario folder
- you should see an image like the one below
- check in Windows Explorer to confirm the scenario folder is still empty
NEXT:
- in project overview, choose "Create new scenario"
- try out all the possibilities
- "Generate new input files" should work
- "Copy input folder from other scenarios in the project." should work
- "Import input files" should work
=> don't create the inputs folder when opening a project + scenario

MANIFEST.in, cea/config.py, cea/default.config, cea/scripts.yml, cea/tests/cooling-case.yml, cea/tests/cooling_case_workflow.py, cea/tests/heating-case.yml, cea/tests/workflow.py
This PR adds a new script `cea workflow` (currently only CLI interface supported) that allows running a "workflow.yml" file. The cooling-case-workflow script is removed and the functionality is merged into the workflow script. To test, in the CEA Console, do:
- `cea workflow --workflow heating-case --resume on`
- `cea workflow --workflow cooling-case --resume on`
These scripts will fail after a while, but show exactly how far our workflows currently go.
An example (first few steps) of a workflow.yml file: 
```
- config: default
"general:multiprocessing": on
"general:project": "{general:project}/../reference-case-open"
"radiation-daysim:daysim-bin-directory": ${RAYPATH}
- script: extract-reference-case
parameters:
destination: "{general:project}/.."
case: open
- config: . …
```
=> Heating case workflow

cea/interfaces/dashboard/plots/routes.py, cea/interfaces/dashboard/plots/static/css/map_layout.css, cea/interfaces/dashboard/plots/templates/layout/grid_layout.html, cea/interfaces/dashboard/plots/templates/modal/new_dashboard.html, cea/plots/base.py
This PR resolves #2236 
Features
---
- Dashboard now has the grid layout, which is similar to the map layout where the map widget is replaced by two plot widgets.
Fixes
---
- Allow the width of the plot widget to grow to fill free space
- Allow plot parameters to load default values if the user has a older `dashboard.yml` that does not contain newly added parameters
=> Feature: Grid Layout for Dashboard

cea/interfaces/dashboard/base/templates/site_template/sidebar.html, cea/interfaces/dashboard/inputs/static/js/mapclass.js, cea/interfaces/dashboard/inputs/templates/table.html, cea/interfaces/dashboard/plots/static/js/map_layout.js
This PR resolves #2208 and resolves #2206 
Changes
---
- Navigation to the input editor in the side navbar is changed to a link instead of a drop down.
Fixes
---
- Map is now able to fully initialize even if the district data is not passed in or is undefined.
- Window does not scroll to the top when clicking table tabs in the input editor.
=> Bugfix: Map not initializing if district data does not exist

cea/config.py, cea/datamanagement/data_helper.py, cea/default.config, cea/inputlocator.py, cea/interfaces/dashboard/tools/static/tools.js, cea/interfaces/dashboard/tools/templates/input_macros.html, cea/tests/create_unittest_data.py, cea/tests/test_calc_thermal_loads.py
This PR updates the `data-helper` tool to allow the user to specify a path for `{data-helper:region}` instead of one of the pre-assigned region values (e.g. "CH" and "SG"). This allows users to create their own region templates.
The data-helper does its best to figure out if the path is a valid region template - defined as containing the same files as the default template (CH database).
In addition, the "technology" database choice was removed, as it didn't work like the other choices - it has been replaced with the parameter `{data-helper:overwrite-technology-folder}` which communicates more clearly what happens - the user can now run the data-helper multiple times _without_ overwriting the regional database (`inputs/technology/*`) by setting `overwrite-technology-folder` to `False`. …
=> FEATURE: allow user-specified region databases for the data-helper

cea/interfaces/dashboard/inputs/static/js/table.js
This PR resolves #2233 
Fixes
-
- User now gets an alert to run data-helper when they try to edit occupancy values in the input editor.
- This works when user tries to edit directly from the table or the selection editor, and it will only prompt the user once every time they visit the input editor and change occupancy.
Testing
-
- Try editing the occupancy from the table then the selection editor, vice versa.
- The alert should only prompt once.
=> Fix: Add alert when user changes occupancy

CHANGELOG.md, CREDITS.md, cea/__init__.py, setup/cityenergyanalyst.nsi
This is the result of the M2.21 sprint which contains new plots as well as changes to how the weather file is used and custom region databases for the data-helper.
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_2.21.exe. See [the guide](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up) for more options.
2019-08-26 - 2.20.3 - #2253 Feature: Supply system map plot @daren-thomas merging as we need it to plan for the 30 sec video for Arno
2019-08-23 - 2.20.3 - #2258 2117 weather as input file
2019-08-23 - 2.20.3 - #2257 FEATURE: lazy loading of cea.api module
2019-08-23 - 2.20.3 - #2252 Fix: Add alert when user changes occupancy @reyery thanks for this!
2019-08-22 - 2.20.3 - #2250 753 global variables removal 2.21 …
=> Updated version number, changelog and credits for 2.21

cea/optimization/preprocessing/decentralized_building_main.py
this PR resolves #2256 
the decentralized script should only run for disconnected heating when the heating demands include space heating.
to test: 
run `cea decentralized`
=> 2256 update conditions to run disconnected_buildings_heating_main

cea/default.config, cea/plots/supply_system/supply_system_map.py
This PR is a first step in solving #2279. The supply map plot is now able to generate a network based on the `supply-system` databases from building properties.
The connectivity of the network would be determined by `supply-system.dbf` with reference to `LCD_infrastructure.xlsx` based on the code e.g. `T1`. It will be connected if the `scale_hs`/`scale_cs` value is equal to `DISTRICT`
Testing
-
- Set the `generation` parameter in `plots-supply-system` to null(empty)
- Run `supply_system_map.py` from plots
- It should open up a new window showing the supply system map with the correct connectivity.
=> 2279 generate network from building supply properties

cea/config.py
This PR resolves #2293 by casting value to a `str` before using lower() when decoding using `BooleanParameter`.
=> Bugfix: BooleanParameter can now decode bool values

cea/resources/radiation_daysim/radiation_main.py
This PR adds a little fix to the `radiation-daysim` script that allows it to be run from PyCharm even if the Daysim binaries aren't in the PATH variable yet - as long as the `cea.config` file points to the correct folder you're good to go.
To test this, 
- make sure the Daysim binaries are not in your PATH variable (e.g., run radiation_main from PyCharm - if it doesn't run through, you should be good for testing)
- make sure `{radiation-daysim:daysim-bin-directory}` is set to a folder containing Daysim binaries (if you installed with the CEA installer, this is given)
- run `radiation_main` from PyCharm. it should now run through.
=> 2019.09.16 run radiation daysim from pycharm

cea/config.py, cea/default.config
Running `cea workflow` was printing an error because the `default.config` used the value `heating-case` as the default - but the only pre-configured workflows are `district-heating-system` and `district-cooling-system`.
This is purely cosmetic - the functionality isn't really affected.
=> BUG: fixed default value for workflow parameter

cea/interfaces/dashboard/inputs/inputs.yml
This PR solves part of #2322.
The variables are now added to the inputs.yml file, which decides which columns are shown in the dashboard input editor.
=> Show Es and Ns variable for architecture in dashboard 

cea/interfaces/dashboard/inputs/static/js/store.js
The PR resolves #2328 
This bug is caused by accessing a nested object property where one of the higher level properties do not exist, thus causing a `TypeError`. This error stops the loop and prevents the edit selection modal from closing after clicking **OK**.
=> Bugfix: Edit selection in input editor does not work if some old values is equal to the new value

cea/datamanagement/data_helper.py
Added a warning for buildings that have equal shares of more than one occupancy type that are bigger than any other occupancy type (i.e., they have more than one "main" use). The warning prints out the following message:
```
B02 has equal share of GYM and HOTEL; the construction properties and systems for GYM will be used.
```
The solution is not as elegant as the original code to define the main use (it iterates through the dataframe instead of using arrays), but it is functional.
=> Clarify main-use determination of buildings with exactly equal use mix

cea/interfaces/dashboard/tools/routes.py, cea/interfaces/dashboard/tools/templates/tool.html
This PR introduces a quick fix that solves the issue where users are not getting the newest version of tools script since their browsers are caching it.
=> Add modified timestamp to tools.js

CHANGELOG.md, CREDITS.md, cea/__init__.py, setup/cityenergyanalyst.nsi
This is the result of the M2.23 sprint which focused mainly on the (upcoming) Electron interface and testing the optimization refactoring - both topics will only be released in the next
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_2.23.exe. See the guide for more options.
2019-10-02 - 2.22 - #2338 Moving flexibility (concept project) to legacy
2019-10-02 - 2.22 - #2353 Project api for electron application
2019-10-02 - 2.22 - #2337 fix to network layout script (EL is not implemented yet) @daren-thomas thanks for checking this out
=> Release 2.23

cea/config.py, cea/datamanagement/weather_helper.py, cea/default.config
This PR addresses #2333 - basically, if the user manually edited the config file to set the `{weather-helper:weather}` to an invalid value, the CEA was just taking the first valid weather file name from its database and working with that.
The new behavior: Raise an error to make it obvious that the config file has a false value.
=> Raise an error for false weather files

cea/interfaces/dashboard/api/__init__.py, cea/interfaces/dashboard/api/glossary.py, cea/interfaces/dashboard/base/routes.py, cea/interfaces/dashboard/dashboard.py, cea/interfaces/dashboard/server/__init__.py
This PR resolves #2358 and resolves #2357
Added
-
- Endpoint `/api/glossary`  to get glossary data
- Endpoint `/server/alive` to check that the flask server is running when launching the electron app
- Endpoint `/server/shutdown` to shutdown the flask server after quitting the electron app
=> Glossary api for electron

cea/interfaces/dashboard/dashboard.py, docs/how-to-create-a-new-release.rst, setup/cityenergyanalyst.nsi
This PR creates an installer for the CEA Electron interface and updates the notes on creating a new release to include providing the CEA Electron interface - which, for now, lives in its own repository and will be developed in lock-step with the rest of the CEA code.
A test-version of the installer can be found here: https://www.dropbox.com/s/nukficzmvq64hyf/Setup_CityEnergyAnalyst_2.23.exe?dl=0
After installation, use the "CEA Dashboard" link from the start menu to open the Electron interface.
=> 2360 create installer for electron interface

setup/cityenergyanalyst.nsi
This PR is a _tiny_ update to the installer to use the newest URL for the CityEnergyAnalyst-GUI. The old URL should still work, but it's better to stay up-to-date.
=> Update URL for CityEnergyAnalyst-GUI

MANIFEST.in, cea/config.py, cea/workflows/workflow.py
This PR addresses #2324 (Resume workflow feature does not work).
To test it, start a workflow:
- `cea workflow --workflow district-heating-system`
Wait for some simulations to finish (e.g. after radiation, which takes a while) and kill the process. Then, restart the workflow:
- `cea workflow --resume on`
The workflow should skip script steps that already passed and continue where it left off.
=> 2324 resume workflow feature

cea/scripts.py
This PR addresses #2375 (CEA failure on Grasshopper) - changes were made to `cea.scripts._get_categories_dict` that made it non-importable in Grasshopper.
Grasshopper runs on an IronPython version that does not have access to pip libraries. That's why `cea.scripts._get_gategories_dict` falls back to `scripts.pickle` to load the categories.
@reyery would you mind testing this, please? It touches code you wrote...
=> Allow importing scripts.py from the Grasshopper interface

cea/datamanagement/schedule_helper.py, cea/demand/electrical_loads.py, cea/demand/schedule_maker/schedule_maker.py
This PR fixes an issue with the `schedule_maker` whereby the variable `number_of_occupants` for the case where the number of occupants should be 0 was never assigned. As a result, buildings with no occupants could not be run.
=> BUGFIX: UnboundLocalError: local variable 'number_of_occupants' referenced before assignment

cea/interfaces/dashboard/server/__init__.py, cea/interfaces/dashboard/tools/routes.py, setup.py
This PR solves #2408 - when closing the CEA GUI, running cea worker processes continued running. With the PR, they are terminated on shutdown of the cea flask server.
To test:
- run the CEA GUI
- open project / scenario
- run a bunch of long-running processes (like `demand` or `thermal-network`)
- observe them in the Task Manager (look for python processes)
- close the CEA GUI
- note the python processes are terminated
=> Terminate running cea worker processes when closing the GUI

CHANGELOG.md, CREDITS.md, cea/__init__.py, setup/cityenergyanalyst.nsi
This is the result of the M2.26 sprint which includes a major refactoring of the databases. You'll need to re-run the `data-helper` tool after installing it. We improved the ventilation strategy to avoid unrealistically high temperatures during the heating season, added gains and losses proportional to the conditioned area and added a feature to cancel simulations in the GUI.
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_2.26.0.exe. [See the guide for more options](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up).
2019-11-15 - 2.25.2 - #2455 2349 suspend simulations
2019-11-14 - 2.25.1 - #2448 Ventilation to avoid unrealistically high temperatures during heating season
2019-11-12 - 2.25.1 - …
=> Release 2.26

cea/demand/building_properties.py
This PR solves issues #2473 and #2474, namely:
1-The wrong window to wall ratio was being used in one calculation in CEA. This has been changed from `bpr.architecture.win_wall=wwr_south` to `bpr.architecture.win_wall=A_win / (A_win + A_wall)`
2-Specifying an incorrect material in the architecture inputs (e.g., `type_shade` 'T4') made buildings be skipped entirely, such that if all buildings had such an incorrect parameter, no architecture parameters would be passed to the demand calculation at all. This has been solved by adding an error message that warns the user which buildings have incorrect input parameters of which type.
=> Window to wall ratio and envelope properties

cea/glossary.csv, cea/interfaces/dashboard/api/inputs.py, cea/interfaces/dashboard/inputs/inputs.yml, cea/interfaces/dashboard/inputs/routes.py
This PR provides a way to implement input validation for the front end, which helps with #2310 and #2141
It introduces a new property **_constraints_** for fields in _input.yaml_, which could be used to specify the range of the field i.e. **_max_**.
A new field type **_choice_** is also added to restrict users to only select values found in a list. 
A property **_location_** is used to extract this list of values from a database.
Other Changes:
Update `technical_systems` to `air_conditioning_systems`
=> Data validation for inputs in front end

cea/interfaces/dashboard/api/dashboard.py, cea/plots/base.py, cea/plots/demand/__init__.py
This PR helps with #2393 and adds an endpoint to the api to return an array of input files used for a plot in the dashboard.
Other changes:
- Add buildings to input files of demand plots if buildings are selected
=> Show plot input files

cea/api.py, cea/interfaces/cli/cli.py
This PR addresses #2395 - Missing input files should create an error and the job info in the CEA GUI should reflect that:
To test, follow steps from the issue (basically, just remove all data-helper output and run radiation)
=> Missing input files should create an error, not a success in the jobs list

cea/resources/radiation_daysim/radiation_main.py
This branch addresses #2447 by checking for the existence of the Radiance/Daysim binaries _before_ running the radiation script.
It uses the value in the config file as a starting point and then checks some other obvious places (Daysim subdirectory of Dependenecies folder as installed by installer, `C:\Daysim\bin`, `%RAYPATH%`).
If the binaries can't be found, an error is raised, otherwise, the simulation is run with the path found.
=> Check for daysim binaries

CHANGELOG.md, CREDITS.md, cea/__init__.py, docs/how-to-create-a-new-release.rst, setup/cityenergyanalyst.nsi
This is the result of the M2.28 sprint. We worked mainly on fixing bugs.
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_2.28.1.exe. [See the guide for more options](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up).
2020-01-14 - 2.27.0 - #2516 fixing small bugs i2512 and i2509
2020-01-14 - 2.27.0 - #2513 fix nominal cap
2020-01-10 - 2.27.0 - #2517 2511 solar plots
2020-01-10 - 2.27.0 - #2499 @daren-thomas well as soon as this fixes the problem of #2502
2020-01-09 - 2.27.0 - #2503 Fix for scenario creation
2020-01-09 - 2.27.0 - #2412 Simplify environment.ubuntu.yml
2020-01-09 - 2.27.0 - #2492 Fixing plots nyc
2020-01-08 - 2.27.0 - #2497 Rtd build errors
2020-01-07 - 2.27.0 - #2498 Missing input …
=> Release 2.28

cea/technologies/substation.py, cea/technologies/thermal_network/simplified_thermal_network.py
- The Hazen-Williams coefficient was wrongly named "Hanzen-Williams"
- "First" was misspelled as "Firs"
- Two pairs functions were named inconsistently with one another
=> Typos and nomenclature in thermal networks

cea/schemas.yml, cea/scripts.yml, notebooks/update_schemas_yml.ipynb
This PR solves #2506 (Add get_database_envelope_systems to schemas.yml (update schemas.yml?)) and adds a jupyter notebook to make this easier in the future.
To test, create a new project with a new scenario.
DO NOT run data-helper.
INSTEAD: run demand. you should be greeted with a list of missing input files and hints how to get them.
=> updated schemas.yml with trace-inputlocator output

cea/default.config, cea/technologies/thermal_network/simplified_thermal_network.py
Was: "min-head-susbstation"; Should be: "min-head-substation"
=> Fixed typo in a variable name

cea/schemas.yml
This PR fixes a small omission in PR #2532: The worksheet name in the `schemas.yml` file for `get_database_supply_systems` is now "DETAILED_ELEC_COSTS".
=> update schemas.yml file to conform to changes in PR 2532

cea/demand/building_properties.py
Some functions in `building_properties.py` were still looping through the envelope properties data frame in order to get the list of buildings in the zone instead of using the correct input locator method. Thus, if there were any additional buildings in the input dbf files the demand script wouldn't work.
=> Use consistent input locator method in building_properties.py

CHANGELOG.md, CREDITS.md, bin/create-changelog.py, cea/__init__.py
This is the result of the M2.31 sprint. We restructured the databases shipped with CEA and fixed some bugs.
**NOTE:** This version uses a scenario format that is incompatible with the one in 2.29.0 (the databases were restructured). If you have an existing scenario, please wait for the next release which will include a migration script to convert it to the new format.
To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_2.30.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.30.0/Setup_CityEnergyAnalyst_2.30.0.exe). 
[See the guide for more options.](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up)
- 2020-02-21 - 2.30.0 - #2590 2586 add electric vehicles …
=> Release 2.31.0

MANIFEST.in
The file `test_technologies.config` (used by the unit test `cea/tests/test_technologies.config`) needs to be in MANIFEST.in for it to be packaged by pip. Adding this to fix master in Jenkins.
=> added test_technologies.config to MANIFEST.in

setup/cityenergyanalyst.nsi
This PR addresses #2596 - it updates the installer to skip a version of pip that was creating an error (`ImportError: Cannot import name 'PackageFinder'`).
Users that have already run into this error will need to uninstall and reinstall the CEA as the faulty version of pip makes bootstrapping its own update impossible.
=> update pip, skipping over the broken version of pip

cea/resources/radiation_daysim/geometry_generator.py
This is a tiny PR to fix the annoying DEBUG log messages from matplotlib, fiona, shapely et al. when running the radiation script with multiprocessing on.
=> suppress DEBUG logging from matplotlib et al when multiprocessing radiation

cea/api.py, cea/config.py
This PR tries to fix #2606 which is caused by some race condition of **multiprocessing** reading/writing `cea.config` file at the same time when running **workflow** script with scripts with  **multiprocessing** on. 
This is caused by multiple factors:
- **multiprocessing** re-importing **workflow** and `cea.api` for each process (how **multiprocessing** works for **Windows** machines)
- `cea.api` creating a new instance of **Configuration** when it is being imported
- `__init__` of **Configuration** object _reads_ then _writes_ the `cea.config` file
- since `cea.config` file is not locked multiple processes could access and modify the file at the same time
This rarely happens but the chance of it happening increases with more processes being used.
To reduce the number of writes by …
=> ConfigParser error in workflow

cea/technologies/thermal_network/simplified_thermal_network.py, cea/utilities/__init__.py
This PR addresses a problem with the Jenkins merge-on-master test: It kept failing in the `decentralized` stage. Turns out, the problem can be traced back to an `os.chdir` in the `thermal-network` script. I've added a utility function `pushd` that can be used with a `with` block that sets the path back to what it was after the `wintr` module is used.
=> move os.chdir to cea.utilities.pushd

cea/resources/radiation_daysim/daysim_main.py, cea/resources/radiation_daysim/geometry_generator.py, cea/resources/radiation_daysim/radiation_main.py, cea/utilities/__init__.py
This PR fixes 
- #2597 (GDAL and DAYSIM environment variables are not set for users running scripts from PyCharm) 
- #2589 (Function checking for DAYSIM binaries for radiation script does not pass binaries installed by DAYSIM installer)
I've tried a bunch of combinations, but please try to break this:
- remove the folder `C:\Daysim` (e.g. rename it to `C:\Daysim.bak`
- remove the Daysim installation from the CEA installer (check the `Dependencies` folder)
Running the scripts works from PyCharm as well as from the command line. I think we're done here.
=> 2597 gdal daysim variables from pycharm

cea/interfaces/dashboard/api/dashboard.py, cea/plots/base.py, cea/plots/cache.py, cea/plots/categories.py
This PR resolves #2628 and add the ability to export plot data to .csv/.xlsx files for users.
This is done by parsing the data found in the plots that are encoded in the Plotly format to pandas dataframes and then exported. That means that this is actually an extra step since we are already calculating the data using dataframes before converting them to the Plotly format. If I'm not wrong, Plotly v3 actually has methods to plot straight from dataframes instead using Plotly graph objects in v2 that we are using now.
The current way it is implemented is more of a workaround than an actual solution. It would not exactly work on mostly plots but works best on plots that are purely made up of bar graph objects. However this should be sufficient for our needs now. I did not want to …
=> Plot data export

cea/__init__.py
This PR addresses #2690 by creating a new Installer based on the current master status.
- I was able to reproduce the bug in #2690 (v3.0.2) after uninstalling and re-installing that version
- based on master, I created the release v3.0.3a0 and tested it (again, after uninstalling v3.0.2)
- I was NOT able to reproduce the bug with the new installer, further, the error I suspected (missing `inputs.yml` in `MANIFEST.in`) has since been fixed in master.
I suggest this PR can be merged as the only change is the new version number.
=> CityEnergyAnalyst v3.0.3a0

cea/inputlocator.py
As discussed in issue #2687 this fix attempts to catch the situation where multiple processes attempt to create the same folder simultaneously. The fix catches a generic OSError, forces a time.sleep of 500ms and checks if the folder was indeed created. 
Since the error is difficult to catch, the following test script can be used (script might need to be run several times in order to catch the error).
```
import os
import time
from multiprocessing import Pool
THIS_DIR = os.path.dirname(os.path.realpath(__file__))
##################################################
def return_folder_name(_):
folder = os.path.join(THIS_DIR, "test_folder")
if not os.path.exists(folder):
try:
print "making a folder"
os.mkdir(folder)
except OSError as e:
print "failed to make a folder"
time.sleep(0.5)
if not …
```
=> added a fix for _ensure_folder method in /cea/inputlocator.py

cea/interfaces/dashboard/plots/routes.py, cea/plots/base.py, cea/plots/demand/comfort_chart.py, cea/plots/demand/peak_load.py, cea/plots/optimization/a_pareto_curve.py, cea/plots/solar_potential/a_solar_radiation.py, cea/plots/thermal_networks/b_demand_curve.py
This PR fixes #2682 and #2683. It changes the **Relative** units for **Peak Demand** from `kW/m2` to `W/m2`. Also updates code to be compatible with the latest **Plotly** version (v4) which allows us to use `rangebreaks` to hide leap day from the x-axis.
Testing:
- Run **Peak Demand** from **Demand** and check the plot on the right
- Use data from a leap year and run `run_all_plots` test to make sure that all plots can be plotted. Solar radiation plot should still have the leap day.
- Update `plotly` using `pip install -U plotly` in the CEA console.
-  Run `run_all_plots` test to make sure that all plots can be plotted. Solar radiation plot should not have the leap day.
Would need to update **Dependencies.7z** to include the new version of **Plotly**
=> Update plotly version

CHANGELOG.md, CREDITS.md, cea/__init__.py, setup.py, setup/cityenergyanalyst.nsi
This is the result of the M3.2 sprint. We fixed some issues with weather files containing leap years and spent some time clarifying our development process as well as other things - see the CHANGELOG for more information.
To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_3.2.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.2.0/Setup_CityEnergyAnalyst_3.2.0.exe). See [the installation guide](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up) for more options.
- 2020-04-30 - 3.1.0 - #2709 Update plotly version
- 2020-04-25 - 3.1.0 - #2678 I2672 roles and responsibility
- 2020-04-24 - 3.1.0 - #2706 Fix epwreader
- 2020-04-22 - 3.1.0 - #2705 update naming …
=> Release 3.2.0

cea/inputlocator.py, cea/schemas.yml, cea/technologies/thermal_network/simplified_thermal_network.py, cea/technologies/thermal_network/thermal_network.py
This PR fixes #2710 by trying to make the outputs of detailed and simplified versions of `thermal-network` to be consistent with each other. It also includes a fix for #2700 by correctly creating choices for plant nodes.
Testing for #2700 would be trying to select a plant node when creating **Heating Reset Curve** plot
=> Thermal network script output format

cea/datamanagement/database_migrator.py, cea/technologies/thermal_network/thermal_network.py
While working on #2667, I made a small performance optimization to the detailed version of the thermal-network script: The results of the `find_loops` method can be cached for a specific input df. This saves a bit of time (maybe 20%). It's still very slow and as far as I can tell, most of that is performing a `np.isclose` call. Those are not really avoidable, _unless_ we can figure out that logically some are redundant. That's an exercise for another day!
=> Small performance optimization for detailed thermal-network script

cea/tests/workflow_slow.yml, cea/workflows/district_cooling_system.yml, cea/workflows/district_heating_system.yml
This PR includes some updates to the `district-cooling-system` workflow - reverting back to using SG weather and databases to force cooling.
To test, use `cea workflow --workflow district-cooling-system`.
The `cea test --workflow slow` is also slightly altered - I'm not sure if it runs through yet. But I think we can merge it anyway.
=> update the district-cooling-system workflow to use SG weather

cea/plots/supply_system/__init__.py
This fixes a potential problem when setting `building_capacities` index if  `building_capacities `is empty  (i.e. `heating_cap` and `cooling_cap` are empty).
Also replaces `NaN` values with 0 when concatenating `heating_cap` and `cooling_cap` since both have different columns and rows.
=> Avoid setting index for empty building_capacities

cea/demand/building_properties.py, cea/demand/control_heating_cooling_systems.py, cea/demand/demand_main.py, cea/demand/electrical_loads.py, cea/demand/hourly_procedure_heating_cooling_system_load.py, cea/demand/sensible_loads.py, cea/demand/space_emission_systems.py, cea/interfaces/dashboard/dashboard.py
This PR fixes #2739 by changing `BuildingProperties` to load input files (e.g. radiation) of selected buildings instead of all buildings in the zone when running **demand**.
Testing:
- Create new scenario with all required input files
- Run radiation for only one building
- Run demand for that one building
=> 2739 Allow running of demand when selecting buildings

cea/config.py, cea/interfaces/dashboard/api/project.py
This PR fixes #2765 by returning an empty list of scenarios if project is non-existent.
TODO:
- Update GUI to show error messages of api calls (exception or unable to contact server) in some sort of popup so user know what to do.
=> Return empty list if unable to find project

CHANGELOG.md, CREDITS.md, cea/__init__.py, cea/constants.py, cea/workflows/workflow.py, docs/graphviz/archetypes_mapper.gv, docs/graphviz/data_initializer.gv, docs/graphviz/optimization.gv, docs/how-to-create-a-new-release.rst, docs/output_methods.rst, docs/script-data-flow.rst
This is the result of the M3.4 sprint. We implemented a plugin architecture - see [CEA Plugins - Part 1: Introduction](https://daren-thomas.github.io/cea-plugins-part-1/) for a preview of the documentation to the plugin architecture. We also added a refinement of the 'chiller_vapor_compression' COP by accounting for partial load operation. And more (see CHANGELOG)
To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_3.4.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.4.0/Setup_CityEnergyAnalyst_3.4.0.exe). See [the installation guide](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up) for more options.
- 2020-06-12 - 3.3.0 - #2771 Update range values
- …
=> Release 3.4.0

cea/plots/base.py
This PR fixes #2773 #2774 #2775 where 'hourly', 'daily' and 'weekly' plots where not being shown. This is likely caused by `rangebreaks` having a value that is in a different format of the plot data.
Testing:
- Remember to clean plot cache
- Try creating time series bar plots i.e. solar radiation, solar collector, photovoltaic
- Switch to each date frame i.e. hourly, daily, weekly, monthly, yearly
=> Fix some timeseries plots not showing

cea/datamanagement/databases_verification.py, cea/datamanagement/zone_helper.py
This PR fixes #2764 by adding a new function to clean geometries from **OpenStreetMap** before processing it.
The issue is mainly caused by `geopandas` not able to export a GeoPandas DataFrame to a shapefile if any of its geometries are of type **`MultiPolygon`**. It solves it by trying to flatten any **`MultiPolygon`** into a single **`Polygon`**.
=> Clean geometries from OpenStreetMap in zone-helper

cea/datamanagement/surroundings_helper.py, cea/datamanagement/zone_helper.py
This PR fixes #2803 by improving the method of parsing `building:levels` data from OSM and adding it to `surroundings-helper` which was missing.
It will now also try to parse `building:levels` if it is a list of numerical values separated by commas or semicolons (since they are quite common based on looking at the possible types of values from http://taginfo.openstreetmap.org), and then return the maximum value from the list.
It returns NaN if it is unable to parse the value.
=> Properly parse `building:levels` data from OSM

cea/config.py, cea/datamanagement/archetypes_mapper.py, cea/default.config, cea/demand/demand_main.py, cea/demand/demand_writers.py, cea/demand/schedule_maker/schedule_maker.py, cea/optimization/master/master_main.py, cea/resources/geothermal.py, cea/schemas.py, cea/technologies/network_layout/main.py, cea/technologies/network_layout/substations_location.py, cea/technologies/solar/photovoltaic_thermal.py, cea/technologies/solar/solar_collector.py
This PR solves #2752 by returning all default technologies for optimization parameters `technologies_DH` and `technologies_DC` if they are empty.
It was also observed that the class `MultiChoiceParameter` in config does not default to using `_choices` if the value in config is empty. Instead, they are manually handled in the scripts. Some examples are `input-databases` for **archetypes-mapper** and `loads-output` for **demand**. I'm not sure if this should be the default behavior but this could be added to the class in another issue.
To test:
Remove all choices in both `technologies_DH` and `technologies_DC` in optimization config and run optimization
=> Select all technologies in optimization if none is selected

CHANGELOG.md, CREDITS.md, cea/__init__.py, cea/config.py, cea/workflows/coverage.yml
This is the result of the M3.7 sprint. We skipped a few releases while we worked on a Python 3 port of the CEA, but felt we need to do at least one more Python 2.7 release with updates and bug fixes.
To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_3.7.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.7.0/Setup_CityEnergyAnalyst_3.7.0.exe). See [the installation guide](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up) for more options.
- 2020-07-27 - 3.4.0 - #2807 Select all technologies in optimization if none is selected
- 2020-07-27 - 3.4.0 - #2806 Properly parse `building:levels` data from OSM
- 2020-07-27 - 3.4.0 - #2767 Clean geometries from …
=> Release 3.7.0

CHANGELOG.md, CREDITS.md, cea/__init__.py
This is the result of the M3.10 sprint. We skipped a few releases while we worked on a Python 3 port of the CEA, but felt we need to do at least one more Python 2.7 release with updates and bug fixes.
Additionally, we improved radiation script runtime using multiprocessing and the new binaries. Users are now able to switch between the old Daysim binaries and the new one.
To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_3.10.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.10.0/Setup_CityEnergyAnalyst_3.10.0.exe). See the [installation guide](https://city-energy-analyst.readthedocs.io/en/latest/installation/installation.html) for more options.
- 2020-09-14 - 3.7.0 - #2828 Introduce new Daysim …
=> Release 3.10.0

README.rst, docs/how-to-create-a-new-release.rst, docs/installation/installation-on-windows.rst
This PR solved #2830 .
The main changes are in the documentation page `How to create a release?`
This updated documentation shows how @reyery and I were able to create the release for v3.10.0.
It would be great if @daren-thomas could verify if that is the correct sequence. 
Also, some links are updated (see file changes).
=> i2830 Update release documentation

.gitignore, CHANGELOG.md, CREDITS.md, bin/create-changelog.py, cea/__init__.py, docs/how-to-create-a-new-release.rst
This is the result of the M3.11 sprint. We completed testing of the  Python 3 port of the CEA and merged it to master.
This is the first official release of the CityEnergyAnalyst running on Python 3.7.8.
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_3.11.0.exe. See the installation guide for more options.
- 2020-09-25 - 3.11.0a5 - #2802 2745 CEA Python3 port (expected release: v3.11.0)
- 2020-09-16 - 3.10.0 - #2831 i2830 Update release documentation
- 2020-09-16 - 3.10.0 - #2829 Release 3.10.0
=> Release 3.11.0

CHANGELOG.md, CREDITS.md, cea/__init__.py
This is the result of the M3.13 sprint. We fixed a bug in the Database Editor - an artefact of the move to Python 3. We're sorry for any inconveniences that might have cause. We also have a working Dockerfile for running the CEA as a headless server.
To install it on windows, download and run the attached Setup_CityEnergyAnalyst_3.13.0.exe. See the installation guide for more options.
- 2020-10-29 - 3.11.0 - #2850 2834 docker container for remap
- 2020-10-29 - 3.11.0 - #2848 2844 database editor bug
- 2020-10-28 - 3.11.0 - #2846 Predefined hourly setpoints definition
- 2020-09-25 - 3.11.0 - #2837 Release 3.11.0
=> Release 3.13.0

cea/scripts.yml
A small fix to make sure construction standards database file exists for `zone-helper` to run.
=> Add construction standards as input dependency of zone-helper

CHANGELOG.md, CREDITS.md, cea/__init__.py, cea/scripts.yml
This is the result of the M3.15 sprint. We added an option for user-supplied PV tilt angle and maximum roof coverage and fixed some bugs.
To install it on windows, download and run the attached `Setup_CityEnergyAnalyst_3.15.0.exe`. See the [installation guide](https://city-energy-analyst.readthedocs.io/en/latest/installation/installation.html) for more options.
- 2020-12-01 - 3.14.0 - #2873 2852 After merging docker image, change the url used to track master
- 2020-11-19 - 3.14.0 - #2853 Add option for user-supplied PV tilt angle and maximum roof coverage
- 2020-11-19 - 3.14.0 - #2857 cea-doc html now works again
- 2020-11-18 - 3.14.0 - #2870 Add construction standards as input dependency of zone-helper
- 2020-11-18 - 3.14.0 - #2824 Change surroundings-helper to use a …
=> CityEnergyAnalyst v3.15.0

cea/interfaces/dashboard/api/inputs.py
Fixed #2871 with @reyery by catching `fiona.errors.DriverError` in `CityEnergyAnalyst/cea/interfaces/dashboard/api/inputs.py `(`df_to_json` and `get_building_properties`). The issue was caused by migration to Python 3.
=> fixed issue #2871 by catching fiona.errors.DriverError

cea/interfaces/dashboard/api/project.py
This PR goes in tandem with a CityEnergyAnalyst-GUI PR (for a branch with the same name)
It solves the issue in #2811 (Scenarios couldn't be deleted anymore). The main problem was that the GUI keeps it's own state for project / scenario-name and when looking up the `scenario-name` on the cea server side, the "old" project was being used.
The HTTP DELETE method now uses a payload ("project") in the wrapper function `check_scenario_exists` to set the project to the value of the payload if it is present.
=> 2811 can t delete scenario

cea/datamanagement/databases_verification.py
Made a fix to the issue by changing the check for minimum floor height. This no longer adds a new column in the DataFrame (that is later shown in OSM) but rather is now checked explicitly.
=> GUI: Removed odd parameter shown in OSM by updation databases_verification.py

cea/interfaces/dashboard/api/project.py, cea/interfaces/dashboard/dashboard.py
This PR resolves #2910 by generating a simplified preview image for scenarios with large number of buildings to prevent it from blocking other requests for too long which makes the GUI unresponsive.
=> Simplify preview image for scenarios with large number of buildings

cea/interfaces/dashboard/api/inputs.py
This PR resolves #2911 by cleaning up how error handling is done during processing network type files.
Hopefully this helps with #2906 as well
Testing
-
Start `cea dashboard` in console first before opening GUI
Try opening a scenario input editor with/without `streets.shp`
Delete `streets.prj` file and open input editor. Input editor should still open but the error will be shown in the console.
=> Remove abort from exception handling

cea/config.py, cea/tests/test_config.py
When calling `config = cea.config.Configuration()`; `FileParameter.decode` isn't interpolating so `config.create_new_scenario.zone` remains as `{general:scenario}/inputs/building-geometry/zone.shp` which breaks `cea.api.create_new_scenario` as `zone_geometry_path = config.create_new_scenario.zone` is not a real filepath.
`config.create_new_scenario.zone` returns a real filepath
- Get `CityEnergyAnalyst`
- `git clone https://github.com/architecture-building-systems/CityEnergyAnalyst`
- `cd <path-to-CityEnergyAnalyst>`
- Setup a local `CityEnergyAnalyst` development environment via `docker`:
-  `docker run --rm -it --entrypoint /bin/bash -v $(pwd):/CityEnergyAnalyst -p 8888:8888 -p 5050:5050 darenthomas/cityenergyanalyst`
- Install latest `cea`:
- `source activate /venv/bin/activate` 
- …
=> Decode FileParameter via regex

cea/datamanagement/zone_helper.py, cea/tests/datamanagement/test_zone_helper.py
When `osmnx.footprints.footprints_from_polygon` returns buildings with `Point` geometries `joined = unary_union(list(geometry))` in `zone_helper.clean_geometries.flatten_geometries` fails as `Point` geometries are not iterable.
`zone_helper.clean_geometries.flatten_geometries` can handle `Point` geometries
- Setup a local `CityEnergyAnalyst` development environment via `docker`:
- `git clone https://github.com/architecture-building-systems/CityEnergyAnalyst`
- `cd CityEnergyAnalyst`
-  `docker run --rm -it --entrypoint /bin/bash --workdir /CityEnergyAnalyst -v $(pwd):/CityEnergyAnalyst darenthomas/cityenergyanalyst`
- `source activate /venv/bin/activate` 
- `pip install -e .`
- Run:
```python
import geopandas as gpd
from shapely.geometry import Point, Polygon
from …
```
=> zone_helper.clean_geometries fails for Point

cea/demand/demand_main.py, cea/demand/demand_writers.py, cea/demand/schedule_maker/schedule_maker.py, cea/schemas.py, cea/technologies/solar/photovoltaic.py
There were some return statements/values that were not used so they were removed to decrease the memory needed to store this return objects. The aggregation step of photovoltaic script now uses multiprocessing to make things faster. Both of these changes might only be noticeable when dealing with larger scenarios.
=> Optimise demand and photovoltaic scripts

cea/schemas.yml
This solves #2962 
Partitions are included in schemas.yml to show up in the interface.
To test: open a scenario, run archetypes mapper if necessary and look for  type_part in the architecture tab
=> included partitions

cea/datamanagement/data_migrator.py, cea/demand/demand_main.py, cea/demand/schedule_maker/schedule_maker.py, cea/schemas.yml, cea/scripts.yml, docs/graphviz/database_migrator.gv, docs/modules/cea.datamanagement.rst, docs/script-data-flow.rst
This PR solves issue #2977 and does the following things:
1. add functions to separately check if the internal loads and indoor comfort inputs and/or the output occupancy schedules need to be updated before doing migration
2. add code to rename column `people_pax` in files in `./outputs/data/occupancy`
3. rename `database_migrator` to `data_migrator` to be consistent with the current functionality
=> 2977 data migrator

cea/datamanagement/terrain_helper.py, cea/resources/radiation_daysim/geometry_generator.py, cea/utilities/standardize_coordinates.py
It seems that `gdal` has to be imported from `osgeo` when using it with Mac and sometimes Linux. This could be something to do with the newer version of `gdal` that is being installed using conda since we do not restrict the version of the `gdal` being installed in the CEA environment. Importing this way seems to work on Windows as well (at least on my computer) but further testing on other computers would need to be done to make sure that this works on Windows as that is where majority of our users are using CEA.
=> Update gdal imports to use osgeo instead

cea/config.py, cea/interfaces/cli/cea_config.py
Plugins can be added to the config using the new tool `cea-config add-plugins NAME_OF_PLUGIN`.
This appends the new plugin to the `general:plugin` config instead of replacing it when using `cea-config write --general:plugins NAME_OF_PLUGIN`
=> Add plugins using cli

.dockerignore, Dockerfile, docs/installation/installation-on-euler.rst
This PR fixes #3015.
Compilation of Daysim is failing in docker when using the `debian` base image. Not sure what is wrong but my guess might be something to do with a possible new `cmake` update? Using `ubuntu` as the base image somehow fixes this.
=> Use ubuntu instead of debian as base image

cea/default.config, cea/technologies/network_layout/main.py, cea/technologies/network_layout/steiner_spanning_tree.py, cea/technologies/network_layout/substations_location.py
Up until now, the network layout tool was also tasked with placing the centralized heating/cooling plant at the building with the highest load. However, users might want to be able to specify plant locations themselves.
Allowing users to do so is actually quite easy! The function `layout_network` does include `plant_building_names` as an input parameter, but it seems to only be used during optimization.
This PR creates an additional parameter in the config file (`config.network_layout.plant_buildings`) such that users can select the building where the plant is located before running the network layout script. This parameter can take no values (i.e., the plant is located in the building with the highest demand), 1 value (the plant location specified by the user), or multiple values.
Some …
=> Allow user to define heating/cooling plant location

cea/demand/schedule_maker/schedule_maker.py
`np.int()` is deprecated. Removing it avoids a warning being printed out for each building when running the schedule maker.
=> Change `np.int()` to `int()`

cea/datamanagement/surroundings_helper.py, cea/datamanagement/zone_helper.py
When OSM data does not include any information on the number of roofs (`roof:levels`), this value is set to 1 for every building in the case study:
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/2ddce1bc8cdd04038fbfcce881deadd35c621ed7/cea/datamanagement/zone_helper.py#L78-L79
According to the [OSM wiki](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings#Roof), this value seems to refer to, say, a pitched roof:
Later on in the script, this value is added to the data on `building:levels` to get the number of floors above ground in the zone shapefile:
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/2ddce1bc8cdd04038fbfcce881deadd35c621ed7/cea/datamanagement/zone_helper.py#L82-L85
So if no information is available on the type of roof the …
=> Make `roof:levels` 0 by default

cea/dev/build.py
Propose to use mamba when building the CEA windows installer instead of conda to try to speed up `cea-dev build`. mamba will be able to solve the conda environment much faster than conda. 
However, it should be noted that this only helps a bit, since the bulk of the time spent during `cea-dev build` is compiling the installer itself.
=> Add mamba to CEA installer build

cea/resources/radiation_daysim/geometry_generator.py
This PR solves #3068. 
The issue is caused by a race condition when trying to create the temporary folder during building geometry creation, using multiprocessing. 
```python
if not os.path.exists(dir_name): <--- 
os.makedirs(dir_name)
```
Surprisingly, this did not occur very often, even when using machines with higher number of processors.
=> Fix race condition when creating building geometries

cea/datamanagement/zone_helper.py
While testing a case study, I found a couple of instances of `LineString` geometry type, which the `zone_helper` was unable to deal with.
After checking, in my specific case study, these were categorized in OSM as "garden" and "way", i.e., neither was an actual building. So the easiest solution is to ignore this geometry type, much like `Point` geometry types are already ignored by CEA.
=> `zone_helper` cannot import LineString geometry types

cea/optimization/preprocessing/decentralized_buildings_cooling.py, cea/optimization/preprocessing/decentralized_buildings_heating.py
This PR resolves #3102 .
The error came from: 
(1) the incorrect/hard-coded value for the number of objectives (`optsearch.fill(3)`).
(2) the initialization of `indexBest=0` is changed to `None`, it was the reason why the first configuration always got picked
To fix the error, the number of objectives is updated to 2 (cost and emission), but it is still hard-coded at the moment.
Some refactoring is also done to avoid hard-coded values for number_of_configurations.
To test:
- Run the same scenario provided in #3102, and check whether the best index is found.
=> 3102 decentralized buildings cooling

cea/default.config, cea/optimization/master/crossover.py
Remove partially matched crossovers form the crossover options, as they only work on chromosomes with unique indices (travelling salesman-type problems)
=> 3105 Remove Partially Matched CX

environment.yml
This closes #3138 by setting the version for the flask dependencies. 
This is a fast fix, but I think we have to upgrade Flask eventually.
=> Fix Flask dependencies

cea/datamanagement/streets_helper.py
This solves part of #3125
The `name` and `highway` properties are removed from the output file of `streets-helper` since they are not always found/available from OSM in certain places on the map, thus causing a possible key error. Furthermore, CEA does not use them anywhere in the code.
=> Remove unnecessary properties from streets geometry

cea/api.py, cea/config.py, cea/interfaces/dashboard/api/project.py
This solves #3149
`config` restrictions were still retained which caused errors when trying to run scripts from `cea.api`
=> Fix import input files

cea/demand/demand_writers.py, cea/demand/thermal_loads.py
Changed the 'demand_writers' and 'thermal_loads' files so that the regular building demand files ('BXXXX.csv') is output regardless of whether debugging is on or off.
Test this functionality by:
1. setting `debug=true` in cea.config
2. creating a new scenario in any of your current test projects
3. running all scripts up until and including 'Building Energy demand'
4. checking the outputs>data>demand folder: are there 'BXXXX.csv' files for each of the buildings in your scenario?
5. running all scripts up until and including 'Thermal Network Part II (simulation)'
If this last script is running successfully, that means all the necessary inputs - including building demand files - are available.
=> create .csv demand file with debugging on

cea/resources/radiation_daysim/radiance.py
To prevent memory errors when writing to the rad file, the strings are written to file after each iteration, instead of storing it in an array (which would increase in size as the number of buildings increases). This results in a small (could be negligible) speed penalty, since there is more I/O operations, but at least it would prevent it from crashing.
=> Fix memory error when writing radiance surfaces

cea/datamanagement/streets_helper.py, cea/datamanagement/surroundings_helper.py, cea/datamanagement/terrain_helper.py
The previous change to these scripts saved the zone and surroundings files in the geographic coordinate systems. This change caused issues in some surface calculations in later scripts.
This change now saves them to the projected coordinated system (with the projection point set to the centroid of the zone), which should rectify the errors in the surface calculations.
=> Fix CRS change

cea/datamanagement/constants.py, cea/datamanagement/zone_helper.py, cea/default.config
This change allows one to eliminate overlapping geometries using a toggle-option in the zone-helper.
To test:
1. Select an area you know has overlapping building geometries (on the map when creating new scenario).
2. Run the zone-helper with the 'fix-overlapping-geometries' set to on under settings.
Alternatively, if you are unsure which areas contain overlapping building geometries, select random dense area (preferably with high and architecturally complex buildings) and run once with the toggle button on and once with toggle off and compare the two.
=> fixing overlapping geometries

.github/workflows/main.yml, .github/workflows/pull.request.yml
This could help improve the speed of GitHub actions test, by reducing the time needed to prepare the environment.
=> Use micromamba instead of miniforge

cea/datamanagement/zone_helper.py
Fixes issue #3218.
This is a quick fix to make CEA get height from OSM when attribute 'height' is existent.
Question: Should the same process be applied in lines 100, 103 and 106? I am a bit confused about this particular part, which seems to be for when the user has defined the geometry.
Comment: The same can be done for surrounding building and I plan to address this in issue #3219
=> Gets building height from OSM in zone helper

cea/technologies/solar/photovoltaic_thermal.py, cea/technologies/solar/solar_collector.py
During aggregation of the solar potential data, the csv is being read by pandas without parsing the `Date` column as `datetime` type (default behavior), but reading it as it is causing the `Date` column values to be parsed as string.
When "summing" 2 dataframes together, pandas will "sum"/concatenate the `Date` column as strings, resulting in a long string of dates.
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/1dc92c5fea5a03085032fc2483b17d686fbf4b22/cea/technologies/solar/photovoltaic_thermal.py#L725
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/1dc92c5fea5a03085032fc2483b17d686fbf4b22/cea/technologies/solar/solar_collector.py#L1017
```
2009-01-01 01:00:00+01:002009-01-01 01:00:00+01:002009-01-01 01:00:00+01:00
```
Setting date as …
=> Fix aggregation for solar potential scripts

cea/default.config, cea/resources/radiation/geometry_generator.py, cea/resources/radiation/main.py, cea/resources/radiation/simplified/main.py, cea/scripts.yml
Created a simplified script for radiation that runs radiation on a subset of buildings in the area and tries to get sample data for each building surface (i.e. average W/m2 for each surface roof, wall, window).
```
cea radiation-simplified --sample-buildings B1005
```
Based on the reference case, choosing the building in the middle as the sample, roofs are quite accurate but the other surfaces are around 50% higher in total. The script also takes half the time needed.
Error could be improved by using more sample buildings, but i have not tested it.
Percentage diff of total
roofs_top_kW,           1.238405
walls_east_kW,          23.794536
walls_north_kW,        49.347508
walls_south_kW,        55.284678
walls_west_kW,          72.813562
windows_east_kW,    26.135608
windows_north_kW, …
=> Simplified radiation script

cea/optimization/master/evaluation.py, cea/optimization/master/master_main.py, cea/optimization/master/optimisation_individual.py, cea/optimization/optimization_main.py
When running in multiprocessing the the 'Individual'-class created using the deap-creator module could not be accessed since it was not set as a global value. This fix omits creating unnecessary global values by introducing an new 'explicit' Individual-class.
=> Fixed deap-creator error

cea/resources/radiation/daysim.py
As described in #3352, there was a typo in the radiation script that caused the input parameter `config.radiation.roof_grid` not to be used:
```
s a typo in calc_sensors_building that causes the issue:
sensor_dir, \
sensor_cord, \
sensor_type, \
sensor_area, \
sensor_orientation, \
sensor_intersection = generate_sensor_surfaces(face,
grid_size.roof if srf_type == "roof" else grid_size.walls,
srf_type,
orientation,
normal,
intersection)
```
(`srf_type` can only be one of the following: `['walls', 'windows', 'roofs']`)
By fixing this typo, the expected behavior is restored.
How to test:
1. Run the radiation script with the default parameters on any case study
2. Run the radiation script with different values for the roof and walls grids
3. Check number of surfaces generated in each case: …
=> Fix typo that caused `roof_grid` parameter to be ignored

cea/optimization_new/containerclasses/energyCarrier.py
I am getting this error when running optimization. My guess that the intention is to select the first row instead of index 0
```python
Traceback (most recent call last):
File "processor.py", line 116, in <module>
function(sys.argv[1])
File "processor.py", line 109, in function
cea_workflow(config)
File "processor.py", line 61, in cea_workflow
workflow(cea_config)
File "/mnt/storage/dev/datastore-1/proc-repositories/e8874b67ddb8eba3d501d3662da854d64bad9f77271d05177b42de18717cd4e0/dcn-cea/processor_sim/CityEnergyAnalyst/cea/workflows/workflow.py", line 83, in main
do_script_step(config, i, step, trace_input)
File "/mnt/storage/dev/datastore-1/proc-repositories/e8874b67ddb8eba3d501d3662da854d64bad9f77271d05177b42de18717cd4e0/dcn-cea/processor_sim/CityEnergyAnalyst/cea/workflows/workflow.py", …
```
=> Fix optimization KeyError

cea/optimization_new/districtEnergySystem.py
With this change, offspring created from mutation and crossover operations are compared against the existing population to determine which ones are novel and prevent duplicates from being added to the population.
This should also make the optimisation script run faster since duplicate systems are not unnecessarily evaluated.
=> Change selection process to prevent duplicates

cea/resources/radiation/radiance.py
Closes #3355
Daysim would have problems parsing the radiance geometry file if there spaces with the polygon identifier, which in this case is the building name.
To test, use a scenario where buildings have spaces in their name.
With this PR, radiation would successfully complete. On master, radiation would fail.
=> Replace whitespaces with underscore in building name

docs/installation/installation-on-macos.rst
Fixes #3372. The link for the automated installation was wrong, I corrected it per @reyery's feedback.
=> Update MacOS installation guide

cea/datamanagement/zone_helper.py, cea/schemas.yml, cea/utilities/standardize_coordinates.py
In addition to the internal CEA handle of `Building Name`, such as B1000, and B1001, this PR updates zone_helper to save additional information, including `house number`, `street name`, `house_name`, `postal code`, city, `residential_type` (to indicate Singapore's HDB), `city`, and `country`.
=> Saving additional info zone helper

cea/inputlocator.py
Closes #3391
This helps with concurrency (e.g. radiation script) since it creates a temporary folder with a randomised name.
=> Use temp directory created by python

cea/demand/demand_writers.py
In line with Issue#3341, this PR remove `nan` values on the` total_energy_demand.csv`, hence, the `nan` values on the `Total_LCA_operation.csv` are no longer the resolved.
How to test it?
1. Run `demand simulation`
2. Check ` total_energy_demand.csv` to see if there are `nan` values
3. Run `operational emissions`
4.  Check ` total_energy_demand.csv` to see if there are `nan` values
=> Update demand_writers to remove nan values.py

cea/optimization_new/districtEnergySystem.py
Network losses as calculated in the networks-script, are negative. Therefore, they need to be subtracted from the network's demand to add them as a load for the supply system.
=> Fix network losses

cea/optimization_new/supplySystem.py
Eliminating components with a capacity of zero from the final supply system structure.
To test, simply run the optimisation script on a district cooling system and look at the resulting optimal supply system structures. All zero-capacity components that were previously printed to the file should now be gone.
=> Eliminating zero-capacity components

cea/optimization_new/containerclasses/supplySystemStructure.py, cea/optimization_new/supplySystem.py
These changes separate energy carriers that are released to the environment and energy carriers that are released to a grid infrastructure in order to correct an issue with the calculation of heat emission values.
=> Seperating release to envrionment and grids

cea/default.config, cea/utilities/standardize_coordinates.py
This PR fixes the bug of inappropriate coordinate system.
Before this PR, for example, Zurich is set in the southern hemisphere using EPSG:32732, however, it is supposed to be set in the northern hemisphere using EPSG:32632. This is causing issues in the coordinates for the sensor points output from the radiation script.
To test it, choose a random case in Zurich and run CEA radiation analysis. Then check the generated geometry.csv file, and see if the coordinates are in the range of (450000, 5000000).
Can I request @yiqiaowang-arch to review this PR? Thanks.
=> fixing inappropriate coordinate system

cea/scripts.yml
Release v.3.35.0 broke the scenario creation for the dashboard, becuase the create-new-scenario script was removed from scripts. This causes the dashboard to fail when creating a new scenario from scratch with the option "Import input files".
To reproduce, use latest master branch and try to set up a new scenario with the option "Import input files".
Error Message:
```
Exception: create_new_scenario: module 'cea.api' has no attribute 'create_new_scenario'
```
=> add create-new-scenario to scripts.yml

.github/workflows/setup_build.yml, setup/cityenergyanalyst.nsi
Fixes:
- Start menu shortcuts pointing to old directory
- Remove "dashboard.bat" after installation
- Default installation path for "all users" mode to "Program Files"
- Cache CEA python env
=> Fix Windows setup bugs

cea/datamanagement/data_initializer.py
The distutils package is deprecated and slated for removal in Python 3.12
Possible fix for https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/3509
=> Use copytree from shutil instead of copy_tree

cea/analysis/costs/equations.py
This introduces a simple fix to calculating annualised capex and opex with an interest rate of 0. This is necessary since the basic annuity formula is undefined for an interest rate of zero.
In addition, the documentation of these methods was updated and a source explaining how the annuity factor is derived has been added.
=> Handling zero interest rates

cea/optimization_new/component.py, cea/optimization_new/supplySystem.py
When performing the 'cascading' activation of the components installed in the supply system, the previous code would erroneously look at the availability of the demand from renewable energy potentials and grids independently of the component category.
This has now been fixed. With the new code:
- Main cooling/heating components (i.e. primary components) would check if their demand could be met by potentials or the grid prior to activation. 
- Supply components (i.e. secondary components) would check if their demand can be satisfied by the remaining renewable energy potentials and/or the grid.
- Lastly, heat rejection components (i.e. tertiary components) would check if the heat they need to reject can be directly expulsed to the environment prior to their activation.
Additionally, a …
=> Fixing interaction between energy potentials and supply system operation

setup/cityenergyanalyst.nsi
Closes #3558
Installer was still showing the install mode options. Removing the macro directly should remove it.
=> Remove `MULTIUSER_PAGE_INSTALLMODE`

cea/optimization/constants.py, cea/optimization/preprocessing/decentralized_buildings_cooling.py
The test of the decentralised optimisation script started failing after merging the databases for the old centralised optimisation and the database for the new centralised optimisation. This PR attempts to fix that test as follows:
Previously, one system tested by the decentralised optimisation was a cooling system, including the vapour-compression chiller with code 'CH3'. 'CH3' has since been removed from the database because of its strong similarity to 'CH2' (only cost curves differed). The chiller tested in the decentralised optimisation is, therefore, also set to CH2.
=> Hotfix-decentralised-optimisaiton-test

cea/datamanagement/databases_verification.py, cea/default.config, cea/demand/building_properties.py, cea/demand/rc_model_SIA.py, cea/resources/radiation/geometry_generator.py, cea/tests/workflow_medium.yml, cea/tests/workflow_slow.yml, cea/workflows/coverage.yml
As discussed in issue #3555, adjacent walls were not considered by CEA by default. This means that there was artificial insolation on attached walls and adiabatic surfaces were neglected (i.e., walls were assumed to be in contact with exterior air). This is not consistent with the SIA and ISO standards on which the calculation is based, but it does have the advantage of somewhat lower simulation times.
Therefore, the parameter has been redefined: rather than users whether they would like to `consider-intersections`, they are now asked whether they would like to `neglect-adjacent-buildings`. The default value is `False`, as that is the more correct simulation method, but users may set this parameter to `True` if they are okay with less accurate simulations in exchange for somewhat faster …
=> Consider adjacent walls by default

cea/interfaces/dashboard/api/tools.py
Add backwards compatibility for v4 GUI with v3 backend.
=> Add tool check endpoint

cea/datamanagement/weather_helper/weather_helper.py
Use shapely "make_valid" function to make sure geometries are valid before combining them.
=> Fix combining invalid geometries in weather-helper

cea/technologies/thermal_network/thermal_network.py
This fixes Issue #3562 
How to test?
Use a smaller scenario and run network part 2 (detailed)
Compare results `DH__velocity_edges_mpers` and `DH__massflow_edges_kgs.csv`
The results (v) in the former .csv and results (m˙) in the latter .csv:
v=ρ⋅Am˙​
Here, v (velocity) depends on m˙ (mass flow rate, check DH__massflow_edges_kgs.csv`) and A (cross-sectional area of the pipe, which depends on the pipe diameter, check `Distribution.xlsx` in the Scenario Input database) and ρ equals 998kg/m3.
Can you be the reviewer of this PR?  @KFSchlager 
Thanks, Zhongming
=> fixing the messing columns for pipe properties

cea/utilities/standardize_coordinates.py
**Describe the PR**
The original `ensure_cpg_file` function was called very frequently whenever `get_zone_geometry` is used. Particularly, when using the energy potential - photovoltaic-thermal panels functionality. In each separate PVT calculation, this function was called around 12 times. 
The original implementation of `ensure_cpg_file` is to just write `zone.cpg` file to desired content: "ISO-8859-1". When using a cloud drive, for example, OneDrive, to sync the scenarios, such frequent writing will cause OneDrive to sync this .cpg file constantly. Sometimes this cloud drive sync will block CEA to write it, causing PermissionError when trying to write this file again, forcing CEA to exit the current batch simulation. For example, my batch of PVT simulation stops at 1728/1752, and it's …
=> rewrite ensure_cpg_file function to prevent frequent file writing

cea/demand/demand_main.py, cea/demand/demand_writers.py, cea/inputlocator.py
Requested by IDP students, adding in Total_demand_hourly.csv on top of the Total_demand(_buildingly).csv.
How to test?
Run demand 
Check >outputs>data>demand>Total_demand_hourly.csv
Does it exist? Is the number correct?
Unfortunately, the naming of the .csv files are not aligned with the equivalents for the PV aggregated results.
=> Requested by IDP students, adding in Total_demand_hourly.csv

cea/interfaces/dashboard/map_layers/solar_irradiance/layers.py
During the radiation simulation, all geometries are converted to the terrain coordinate system, including the sensor positions. This fixes the bug where the original zone geometry is not in a projection system similar to terrain. Causing the sensor positions to be shown somewhere else on the map.
=> Convert coordinate system based on terrain instead of zone

cea/datamanagement/__init__.py
Enable caching to reduce chance of timeouts due to API rate limiting (default is True)
=> Enable caching for osmnx
